prompt --install
@application/set_environment.sql
@application/delete_application.sql
@application/create_application.sql
@application/shared_components/navigation/lists/bug_synchronization_options.sql
@application/shared_components/navigation/lists/products_nav_bar.sql
@application/shared_components/navigation/lists/application_navigation.sql
@application/shared_components/navigation/lists/bug_actions.sql
@application/shared_components/navigation/lists/navigation_bar.sql
@application/shared_components/navigation/lists/product_cards.sql
@application/shared_components/navigation/lists/access_control.sql
@application/shared_components/navigation/lists/data_load_process_train_upload_bugs.sql
@application/shared_components/navigation/lists/preferences.sql
@application/shared_components/navigation/lists/mobile_menu.sql
@application/shared_components/navigation/lists/bug_loading.sql
@application/shared_components/navigation/lists/manage_repository.sql
@application/shared_components/navigation/lists/activity_reports.sql
@application/shared_components/navigation/lists/reports.sql
@application/plugin_settings.sql
@application/shared_components/security/authorizations/administration_rights.sql
@application/shared_components/security/authorizations/contribution_rights.sql
@application/shared_components/security/authorizations/application_sentry.sql
@application/shared_components/navigation/navigation_bar.sql
@application/shared_components/logic/application_processes.sql
@application/shared_components/logic/application_items.sql
@application/shared_components/logic/application_computations.sql
@application/shared_components/logic/application_settings.sql
@application/shared_components/navigation/tabs/standard.sql
@application/shared_components/navigation/tabs/parent.sql
@application/shared_components/user_interface/lovs/access_control_scope.sql
@application/shared_components/user_interface/lovs/access_control_scope1.sql
@application/shared_components/user_interface/lovs/access_levels.sql
@application/shared_components/user_interface/lovs/bugs.sql
@application/shared_components/user_interface/lovs/bugs_with_bug_number.sql
@application/shared_components/user_interface/lovs/categorylist.sql
@application/shared_components/user_interface/lovs/choose_fix_by_version_based_on_product_id.sql
@application/shared_components/user_interface/lovs/column_names.sql
@application/shared_components/user_interface/lovs/created_or_closed_or_both.sql
@application/shared_components/user_interface/lovs/data_load_option.sql
@application/shared_components/user_interface/lovs/delete_mode.sql
@application/shared_components/user_interface/lovs/filter_report_type.sql
@application/shared_components/user_interface/lovs/first_row_option.sql
@application/shared_components/user_interface/lovs/grouplist.sql
@application/shared_components/user_interface/lovs/grouplist_with_null_option.sql
@application/shared_components/user_interface/lovs/new_or_existing.sql
@application/shared_components/user_interface/lovs/notification_type.sql
@application/shared_components/user_interface/lovs/numbers_1_to_9.sql
@application/shared_components/user_interface/lovs/pill_display_as.sql
@application/shared_components/user_interface/lovs/product_list_with_new_product_option.sql
@application/shared_components/user_interface/lovs/productlist.sql
@application/shared_components/user_interface/lovs/productlist_with_id.sql
@application/shared_components/user_interface/lovs/rows.sql
@application/shared_components/user_interface/lovs/severity.sql
@application/shared_components/user_interface/lovs/show_open_or_closed_or_both.sql
@application/shared_components/user_interface/lovs/since.sql
@application/shared_components/user_interface/lovs/statuslist.sql
@application/shared_components/user_interface/lovs/timeframe_1_year.sql
@application/shared_components/user_interface/lovs/urgencylist.sql
@application/shared_components/user_interface/lovs/userlist.sql
@application/shared_components/user_interface/lovs/username_format.sql
@application/shared_components/user_interface/lovs/userslist_with_null_option.sql
@application/shared_components/user_interface/lovs/version_list_p48.sql
@application/shared_components/user_interface/lovs/yes_y_no_n.sql
@application/pages/page_groups.sql
@application/shared_components/navigation/breadcrumbs/pagenavigator.sql
@application/shared_components/user_interface/templates/page/standard.sql
@application/shared_components/user_interface/templates/page/left_side_column.sql
@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@application/shared_components/user_interface/templates/page/login.sql
@application/shared_components/user_interface/templates/page/master_detail.sql
@application/shared_components/user_interface/templates/page/modal_dialog.sql
@application/shared_components/user_interface/templates/page/right_side_column.sql
@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@application/shared_components/user_interface/templates/button/icon.sql
@application/shared_components/user_interface/templates/button/text_with_icon.sql
@application/shared_components/user_interface/templates/button/text.sql
@application/shared_components/user_interface/templates/region/inline_popup.sql
@application/shared_components/user_interface/templates/region/content_block.sql
@application/shared_components/user_interface/templates/region/alert.sql
@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@application/shared_components/user_interface/templates/region/title_bar.sql
@application/shared_components/user_interface/templates/region/buttons_container.sql
@application/shared_components/user_interface/templates/region/collapsible.sql
@application/shared_components/user_interface/templates/region/interactive_report.sql
@application/shared_components/user_interface/templates/region/standard.sql
@application/shared_components/user_interface/templates/region/wizard_container.sql
@application/shared_components/user_interface/templates/region/inline_dialog.sql
@application/shared_components/user_interface/templates/region/hero.sql
@application/shared_components/user_interface/templates/region/login.sql
@application/shared_components/user_interface/templates/region/carousel_container.sql
@application/shared_components/user_interface/templates/region/tabs_container.sql
@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@application/shared_components/user_interface/templates/list/badge_list.sql
@application/shared_components/user_interface/templates/list/links_list.sql
@application/shared_components/user_interface/templates/list/media_list.sql
@application/shared_components/user_interface/templates/list/menu_bar.sql
@application/shared_components/user_interface/templates/list/wizard_progress.sql
@application/shared_components/user_interface/templates/list/cards.sql
@application/shared_components/user_interface/templates/list/navigation_bar.sql
@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@application/shared_components/user_interface/templates/list/tabs.sql
@application/shared_components/user_interface/templates/list/menu_popup.sql
@application/shared_components/user_interface/templates/report/timeline.sql
@application/shared_components/user_interface/templates/report/media_list.sql
@application/shared_components/user_interface/templates/report/badge_list.sql
@application/shared_components/user_interface/templates/report/comments.sql
@application/shared_components/user_interface/templates/report/search_results.sql
@application/shared_components/user_interface/templates/report/standard.sql
@application/shared_components/user_interface/templates/report/alerts.sql
@application/shared_components/user_interface/templates/report/cards.sql
@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@application/shared_components/user_interface/templates/label/required_floating.sql
@application/shared_components/user_interface/templates/label/optional_floating.sql
@application/shared_components/user_interface/templates/label/hidden.sql
@application/shared_components/user_interface/templates/label/optional.sql
@application/shared_components/user_interface/templates/label/required.sql
@application/shared_components/user_interface/templates/label/optional_above.sql
@application/shared_components/user_interface/templates/label/required_above.sql
@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@application/shared_components/user_interface/templates/popuplov.sql
@application/shared_components/user_interface/templates/calendar/calendar.sql
@application/shared_components/user_interface/themes.sql
@application/shared_components/user_interface/theme_style.sql
@application/shared_components/user_interface/theme_files.sql
@application/shared_components/user_interface/theme_display_points.sql
@application/shared_components/user_interface/template_opt_groups.sql
@application/shared_components/user_interface/template_options.sql
@application/shared_components/logic/build_options.sql
@application/shared_components/globalization/language.sql
@application/shared_components/globalization/messages.sql
@application/shared_components/globalization/dyntranslations.sql
@application/shared_components/user_interface/shortcuts/timezone.sql
@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@application/shared_components/security/authentications/application_express_accounts.sql
@application/shared_components/plugins/region_type/com_oracle_apex_acl_status.sql
@application/shared_components/plugins/region_type/com_oracle_auth_administration.sql
@application/shared_components/plugins/region_type/com_oracle_apex_timelinestatuslist.sql
@application/shared_components/plugins/region_type/com_oracle_apex_badge_list.sql
@application/shared_components/plugins/region_type/com_oracle_apex_acl_warning.sql
@application/shared_components/plugins/region_type/com_oracle_apex_html5_bar_chart.sql
@application/shared_components/plugins/region_type/com_oracle_apex_translated_message.sql
@application/shared_components/plugins/region_type/com_oracle_apex_minicalendar.sql
@application/shared_components/plugins/region_type/com_oracle_apex_validator.sql
@application/shared_components/plugins/region_type/com_oracle_apex_completeness.sql
@application/shared_components/plugins/region_type/com_oracle_apex_tag_cloud.sql
@application/shared_components/plugins/item_type/com_oracle_apex_tags.sql
@application/shared_components/plugins/item_type/com_oracle_apex_simple_checkbox.sql
@application/shared_components/data_loading/tables/eba_bt_sw_defects.sql
@application/user_interfaces.sql
@application/user_interfaces/combined_files.sql
@application/pages/page_00000.sql
@application/pages/page_00001.sql
@application/pages/page_00002.sql
@application/pages/page_00003.sql
@application/pages/page_00004.sql
@application/pages/page_00005.sql
@application/pages/page_00006.sql
@application/pages/page_00007.sql
@application/pages/page_00008.sql
@application/pages/page_00009.sql
@application/pages/page_00010.sql
@application/pages/page_00011.sql
@application/pages/page_00012.sql
@application/pages/page_00013.sql
@application/pages/page_00014.sql
@application/pages/page_00015.sql
@application/pages/page_00016.sql
@application/pages/page_00017.sql
@application/pages/page_00018.sql
@application/pages/page_00019.sql
@application/pages/page_00020.sql
@application/pages/page_00021.sql
@application/pages/page_00022.sql
@application/pages/page_00023.sql
@application/pages/page_00024.sql
@application/pages/page_00025.sql
@application/pages/page_00026.sql
@application/pages/page_00027.sql
@application/pages/page_00028.sql
@application/pages/page_00029.sql
@application/pages/page_00030.sql
@application/pages/page_00031.sql
@application/pages/page_00032.sql
@application/pages/page_00033.sql
@application/pages/page_00034.sql
@application/pages/page_00035.sql
@application/pages/page_00036.sql
@application/pages/page_00037.sql
@application/pages/page_00038.sql
@application/pages/page_00039.sql
@application/pages/page_00040.sql
@application/pages/page_00041.sql
@application/pages/page_00042.sql
@application/pages/page_00043.sql
@application/pages/page_00044.sql
@application/pages/page_00045.sql
@application/pages/page_00046.sql
@application/pages/page_00047.sql
@application/pages/page_00048.sql
@application/pages/page_00049.sql
@application/pages/page_00050.sql
@application/pages/page_00051.sql
@application/pages/page_00052.sql
@application/pages/page_00053.sql
@application/pages/page_00054.sql
@application/pages/page_00055.sql
@application/pages/page_00056.sql
@application/pages/page_00057.sql
@application/pages/page_00058.sql
@application/pages/page_00059.sql
@application/pages/page_00060.sql
@application/pages/page_00061.sql
@application/pages/page_00062.sql
@application/pages/page_00063.sql
@application/pages/page_00064.sql
@application/pages/page_00065.sql
@application/pages/page_00066.sql
@application/pages/page_00067.sql
@application/pages/page_00068.sql
@application/pages/page_00069.sql
@application/pages/page_00070.sql
@application/pages/page_00071.sql
@application/pages/page_00072.sql
@application/pages/page_00073.sql
@application/pages/page_00074.sql
@application/pages/page_00075.sql
@application/pages/page_00076.sql
@application/pages/page_00077.sql
@application/pages/page_00078.sql
@application/pages/page_00079.sql
@application/pages/page_00080.sql
@application/pages/page_00081.sql
@application/pages/page_00082.sql
@application/pages/page_00083.sql
@application/pages/page_00084.sql
@application/pages/page_00085.sql
@application/pages/page_00086.sql
@application/pages/page_00087.sql
@application/pages/page_00088.sql
@application/pages/page_00089.sql
@application/pages/page_00090.sql
@application/pages/page_00091.sql
@application/pages/page_00092.sql
@application/pages/page_00093.sql
@application/pages/page_00094.sql
@application/pages/page_00095.sql
@application/pages/page_00096.sql
@application/pages/page_00101.sql
@application/pages/page_00102.sql
@application/pages/page_00175.sql
@application/pages/page_00420.sql
@application/pages/page_01000.sql
@application/pages/page_01001.sql
@application/end_environment.sql
