<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="OrderService"
     targetNamespace="http://model/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://model/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="UpdateOrderWsdl">
        <plnk:role name="Order" portType="tns:Order"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://model/" location="oramds:/apps/CustomWSDLs/updateOrderJavaWS.wsdl"/>
</wsdl:definitions>
