<?xml version="1.0"?>
<wsdl:definitions
    
     targetNamespace="http://www.oracle.com/ProcessOrder"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://www.oracle.com/ProcessOrder"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:types="http://www.oracle.com/soasample"
    >
    <wsdl:types>
        <xsd:schema>
            <xsd:import schemaLocation="../Schemas/CanonicalOrder.xsd" namespace="http://www.oracle.com/soasample"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="orderInput">
        <wsdl:part name="order" element="types:Order"/>
    </wsdl:message>
    <wsdl:message name="orderOutput">
        <wsdl:part name="ack" element="types:OrderAck"/>
    </wsdl:message>
    <wsdl:portType name="processOrderPortType">
        <wsdl:operation name="process">
            <wsdl:input message="tns:orderInput"/>
            <wsdl:output message="tns:orderOutput"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
