<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://model/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://model/" name="OrderService">
<types>
<xsd:schema>
<xsd:import namespace="http://model/" schemaLocation="../Schemas/updateOrderJava.xsd"/>
</xsd:schema>
</types>
<message name="updateOrder">
<part name="parameters" element="tns:updateOrder"/>
</message>
<message name="updateOrderResponse">
<part name="parameters" element="tns:updateOrderResponse"/>
</message>
<portType name="Order">
<operation name="updateOrder">
<input wsam:Action="http://model/Order/updateOrderRequest" message="tns:updateOrder"/>
<output wsam:Action="http://model/Order/updateOrderResponse" message="tns:updateOrderResponse"/>
</operation>
</portType>
<binding name="updateOrderBinding" type="tns:Order">
<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="updateOrder">
<soap12:operation soapAction=""/>
<input>
<soap12:body use="literal"/>
</input>
<output>
<soap12:body use="literal"/>
</output>
</operation>
</binding>
<service name="OrderService">
<port name="updateOrder" binding="tns:updateOrderBinding">
<soap12:address location="http://localhost:7001/UpdateOrderApp-Model-context-root/updateOrder"/>
</port>
</service>
</definitions>