--------------------------------------------------------
--  File created - Tuesday-November-03-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PURCHASEORDER
--------------------------------------------------------

DROP TABLE "FD_ADMIN"."PURCHASEORDER"
/
  CREATE TABLE "FD_ADMIN"."PURCHASEORDER" 
   (	"ORDERNUMBER" NUMBER(*,0) DEFAULT 12345678, 
	"OLDORDERNUMBER" NUMBER(*,0) DEFAULT 87654321
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
/
Insert into FD_ADMIN.PURCHASEORDER (ORDERNUMBER,OLDORDERNUMBER) values (112,87654321)
/
COMMIT
/
