<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://www.oracle.com/soasample" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/writeOrderToDatabase"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/DemoApp/dbmap/BPELProcess1"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/e2e_1201_composites/ProcessOrderTemplate/validateAndProcessOrder"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/e2e-1201-composites/ProcessOrderTemplate/writeOrderToDatabase">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/validateAndProcessOrder.wsdl"/>
                <oracle-xsl-mapper:rootElement name="Order" namespace="http://www.oracle.com/soasample"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/writeOrderToDatabase.wsdl"/>
                <oracle-xsl-mapper:rootElement name="E2E1201_OrdersCollection"
                                               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/writeOrderToDatabase"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.2.0.0(XSLT Build 130323.0142.4249) AT [THU APR 04 16:46:32 PDT 2013].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:E2E1201_OrdersCollection>
            <tns:E2E1201_Orders>
                <tns:orderNumber>
                    <xsl:value-of select="/ns0:Order/ns0:OrderNumber"/>
                </tns:orderNumber>
                <tns:orderDate>
                    <xsl:value-of select="xp20:current-date ( )"/>
                </tns:orderDate>
                <tns:totalAmount>
                    <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:AuthorizationAmount"/>
                </tns:totalAmount>
                <tns:email>
                    <xsl:value-of select="/ns0:Order/ns0:Email"/>
                </tns:email>
                <tns:status>
                    <xsl:value-of select="/ns0:Order/ns0:Status"/>
                </tns:status>
                <tns:e2E1201_BillinginfoCollection>
                    <tns:E2E1201_Billinginfo>
                        <tns:billingId>
                            <xsl:value-of select="/ns0:Order/ns0:OrderNumber"/>
                        </tns:billingId>
                        <tns:cardpaymenttype>
                            <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:CardPaymentType"/>
                        </tns:cardpaymenttype>
                        <tns:cardnum>
                            <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:CardNum"/>
                        </tns:cardnum>
                        <tns:expiredate>
                            <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:ExpireDate"/>
                        </tns:expiredate>
                        <tns:cardname>
                            <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:CardName"/>
                        </tns:cardname>
                        <tns:authorizationdate>
                            <xsl:value-of select="xp20:current-date ( )"/>
                        </tns:authorizationdate>
                        <tns:addressId>
                            <tns:addressId>
                                <xsl:value-of select="/ns0:Order/ns0:OrderNumber * 100"/>
                            </tns:addressId>
                            <tns:firstName>
                                <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:BillingAddress/ns0:FirstName"/>
                            </tns:firstName>
                            <tns:lastName>
                                <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:BillingAddress/ns0:LastName"/>
                            </tns:lastName>
                            <tns:addressLine1>
                                <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:BillingAddress/ns0:AddressLine"/>
                            </tns:addressLine1>
                            <tns:city>
                                <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:BillingAddress/ns0:City"/>
                            </tns:city>
                            <tns:state>
                                <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:BillingAddress/ns0:State"/>
                            </tns:state>
                            <tns:zipCode>
                                <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:BillingAddress/ns0:ZipCode"/>
                            </tns:zipCode>
                            <tns:phone>
                                <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:BillingAddress/ns0:PhoneNumber"/>
                            </tns:phone>
                        </tns:addressId>
                    </tns:E2E1201_Billinginfo>
                </tns:e2E1201_BillinginfoCollection>
                <tns:e2E1201_OrderItemsCollection>
                    <xsl:for-each select="/ns0:Order/ns0:Items/ns0:Item">
                        <tns:E2E1201_OrderItems>
                            <tns:itemId>
                                <xsl:value-of select="position ( )"/>
                            </tns:itemId>
                            <tns:sku>
                                <xsl:value-of select="ns0:SKU"/>
                            </tns:sku>
                            <tns:quantity>
                                <xsl:value-of select="ns0:Quantity"/>
                            </tns:quantity>
                            <tns:unitprice>
                                <xsl:value-of select="ns0:UnitPrice"/>
                            </tns:unitprice>
                            <tns:brand>
                                <xsl:value-of select="ns0:Brand"/>
                            </tns:brand>
                            <tns:model>
                                <xsl:value-of select="ns0:Model"/>
                            </tns:model>
                            <tns:categoryId>
                                <xsl:value-of select="ns0:Category"/>
                            </tns:categoryId>
                            <tns:description>
                                <xsl:value-of select="ns0:Description"/>
                            </tns:description>
                        </tns:E2E1201_OrderItems>
                    </xsl:for-each>
                </tns:e2E1201_OrderItemsCollection>
                <tns:e2E1201_ShippinginfoCollection>
                    <tns:E2E1201_Shippinginfo>
                        <tns:shippingId>
                            <xsl:value-of select="/ns0:Order/ns0:OrderNumber"/>
                        </tns:shippingId>
                        <tns:shipspeed>
                            <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:ShippingSpeed"/>
                        </tns:shipspeed>
                        <tns:addressId>
                            <tns:addressId>
                                <xsl:value-of select="/ns0:Order/ns0:OrderNumber"/>
                            </tns:addressId>
                            <tns:firstName>
                                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:FirstName"/>
                            </tns:firstName>
                            <tns:lastName>
                                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:LastName"/>
                            </tns:lastName>
                            <tns:addressLine1>
                                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:AddressLine"/>
                            </tns:addressLine1>
                            <tns:city>
                                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:City"/>
                            </tns:city>
                            <tns:state>
                                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:State"/>
                            </tns:state>
                            <tns:zipCode>
                                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:ZipCode"/>
                            </tns:zipCode>
                            <tns:phone>
                                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:PhoneNumber"/>
                            </tns:phone>
                        </tns:addressId>
                    </tns:E2E1201_Shippinginfo>
                </tns:e2E1201_ShippinginfoCollection>
            </tns:E2E1201_Orders>
        </tns:E2E1201_OrdersCollection>
    </xsl:template>
</xsl:stylesheet>
