<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://www.flexagon.com/order"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://www.flexagon.com/OrderEBM"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="OrderEBM.xsd"/>
        <oracle-xsl-mapper:rootElement name="OrderEBM" namespace="http://www.flexagon.com/OrderEBM"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="XMLSchema_-4901770.xsd"/>
        <oracle-xsl-mapper:rootElement name="Order" namespace="http://www.flexagon.com/order"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED AUG 27 15:38:56 CDT 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:Order>
      <tns:OrderNumber>
        <xsl:value-of select="/ns0:OrderEBM/ns0:OrderID"/>
      </tns:OrderNumber>
      <tns:AddressLine>
        <xsl:value-of select="/ns0:OrderEBM/ns0:Address"/>
      </tns:AddressLine>
      <tns:ShippingSpeed>
        <xsl:value-of select="/ns0:OrderEBM/ns0:ShippingMode"/>
      </tns:ShippingSpeed>
      <xsl:if test="/ns0:OrderEBM/ns0:Quantity">
        <tns:Quantity>
          <xsl:value-of select="/ns0:OrderEBM/ns0:Quantity"/>
        </tns:Quantity>
      </xsl:if>
      <tns:ItemNumber>
        <xsl:value-of select="/ns0:OrderEBM/ns0:ItemId"/>
      </tns:ItemNumber>
      <tns:Status>Ready</tns:Status>
    </tns:Order>
  </xsl:template>
</xsl:stylesheet>
