package flexagon.fusion.hrdemo.model.views;

import flexagon.fusion.hrdemo.model.entities.DepartmentsEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 20 17:26:05 CDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsDefaultVORowImpl
  extends ViewRowImpl
{


  public static final int ENTITY_DEPARTMENTSEO = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    DepartmentId,
    DepartmentName,
    ManagerId,
    LocationId,
    Employees,
    JobHistory;
    static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
  public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
  public static final int MANAGERID = AttributesEnum.ManagerId.index();
  public static final int LOCATIONID = AttributesEnum.LocationId.index();
  public static final int EMPLOYEES = AttributesEnum.Employees.index();
  public static final int JOBHISTORY = AttributesEnum.JobHistory.index();

  /**
   * This is the default constructor (do not remove).
   */
  public DepartmentsDefaultVORowImpl()
  {
  }

  /**
   * Gets DepartmentsEO entity object.
   * @return the DepartmentsEO
   */
  public DepartmentsEOImpl getDepartmentsEO()
  {
    return (DepartmentsEOImpl) getEntity(ENTITY_DEPARTMENTSEO);
  }

  /**
   * Gets the attribute value for DEPARTMENT_ID using the alias name DepartmentId.
   * @return the DEPARTMENT_ID
   */
  public Integer getDepartmentId()
  {
    return (Integer) getAttributeInternal(DEPARTMENTID);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name DepartmentId.
   * @param value value to set the DEPARTMENT_ID
   */
  public void setDepartmentId(Integer value)
  {
    setAttributeInternal(DEPARTMENTID, value);
  }

  /**
   * Gets the attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
   * @return the DEPARTMENT_NAME
   */
  public String getDepartmentName()
  {
    return (String) getAttributeInternal(DEPARTMENTNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
   * @param value value to set the DEPARTMENT_NAME
   */
  public void setDepartmentName(String value)
  {
    setAttributeInternal(DEPARTMENTNAME, value);
  }

  /**
   * Gets the attribute value for MANAGER_ID using the alias name ManagerId.
   * @return the MANAGER_ID
   */
  public Integer getManagerId()
  {
    return (Integer) getAttributeInternal(MANAGERID);
  }

  /**
   * Sets <code>value</code> as attribute value for MANAGER_ID using the alias name ManagerId.
   * @param value value to set the MANAGER_ID
   */
  public void setManagerId(Integer value)
  {
    setAttributeInternal(MANAGERID, value);
  }

  /**
   * Gets the attribute value for LOCATION_ID using the alias name LocationId.
   * @return the LOCATION_ID
   */
  public Integer getLocationId()
  {
    return (Integer) getAttributeInternal(LOCATIONID);
  }

  /**
   * Sets <code>value</code> as attribute value for LOCATION_ID using the alias name LocationId.
   * @param value value to set the LOCATION_ID
   */
  public void setLocationId(Integer value)
  {
    setAttributeInternal(LOCATIONID, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link Employees.
   */
  public RowIterator getEmployees()
  {
    return (RowIterator) getAttributeInternal(EMPLOYEES);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link JobHistory.
   */
  public RowIterator getJobHistory()
  {
    return (RowIterator) getAttributeInternal(JOBHISTORY);
  }
}

