package flexagon.fusion.hrdemo.model.views;

import flexagon.fusion.hrdemo.model.entities.RegionsEOImpl;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 20 17:26:07 CDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegionsDefaultVORowImpl
  extends ViewRowImpl
{

  public static final int ENTITY_REGIONSEO = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    RegionId,
    RegionName,
    Countries;
    static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int REGIONID = AttributesEnum.RegionId.index();
  public static final int REGIONNAME = AttributesEnum.RegionName.index();
  public static final int COUNTRIES = AttributesEnum.Countries.index();

  /**
   * This is the default constructor (do not remove).
   */
  public RegionsDefaultVORowImpl()
  {
  }

  /**
   * Gets RegionsEO entity object.
   * @return the RegionsEO
   */
  public RegionsEOImpl getRegionsEO()
  {
    return (RegionsEOImpl) getEntity(ENTITY_REGIONSEO);
  }

  /**
   * Gets the attribute value for REGION_ID using the alias name RegionId.
   * @return the REGION_ID
   */
  public BigDecimal getRegionId()
  {
    return (BigDecimal) getAttributeInternal(REGIONID);
  }

  /**
   * Sets <code>value</code> as attribute value for REGION_ID using the alias name RegionId.
   * @param value value to set the REGION_ID
   */
  public void setRegionId(BigDecimal value)
  {
    setAttributeInternal(REGIONID, value);
  }

  /**
   * Gets the attribute value for REGION_NAME using the alias name RegionName.
   * @return the REGION_NAME
   */
  public String getRegionName()
  {
    return (String) getAttributeInternal(REGIONNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for REGION_NAME using the alias name RegionName.
   * @param value value to set the REGION_NAME
   */
  public void setRegionName(String value)
  {
    setAttributeInternal(REGIONNAME, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link Countries.
   */
  public RowIterator getCountries()
  {
    return (RowIterator) getAttributeInternal(COUNTRIES);
  }
}

