<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.oracle.com/soasample"
                     xmlns:WL5G3N2="http://www.oracle.com/ValidatePayment"
                     xmlns:WL5G3N3="http://schemas.xmlsoap.org/wsdl/soap/"
                     targetNamespace="http://www.oracle.com/ValidatePayment">
  <WL5G3N0:types>
    <xsd:schema xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.oracle.com/ValidatePayment"
                xmlns:types="http://www.oracle.com/soasample" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.oracle.com/soasample"/>
      <xsd:import namespace="http://www.oracle.com/soasample" schemaLocation="../Schemas/CanonicalOrder.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="validateInput">
    <WL5G3N0:part element="WL5G3N1:PaymentInfo" name="paymentInfo"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="validateOutput">
    <WL5G3N0:part element="WL5G3N1:PaymentStatus" name="status"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="validatePaymentPortType">
    <WL5G3N0:operation name="validate">
      <WL5G3N0:input message="WL5G3N2:validateInput"/>
      <WL5G3N0:output message="WL5G3N2:validateOutput"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="validatePaymentBinding" type="WL5G3N2:validatePaymentPortType">
    <WL5G3N3:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="validate">
      <WL5G3N3:operation soapAction="validate" style="document"/>
      <WL5G3N0:input>
        <WL5G3N3:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N3:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="validatePaymentBindingQSService">
    <WL5G3N0:documentation>OSB Service</WL5G3N0:documentation>
    <WL5G3N0:port binding="WL5G3N2:validatePaymentBinding" name="validatePaymentBindingQSPort">
      <WL5G3N3:address location="http://devlnx08:8001/ValidatePayment/ValidatePS?wsdl"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>
