<wsdl:definitions
     name="dbRead"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProcessPurchaseOrder/ProcessPurchaseOrder/dbRead"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProcessPurchaseOrder/ProcessPurchaseOrder/dbRead"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbRead"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbRead_plt" >
    <plt:role name="dbRead_role" >
      <plt:portType name="tns:dbRead_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbRead" schemaLocation="../Schemas/dbRead_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="dbReadSelect_inputParameters">
        <wsdl:part name="dbReadSelect_inputParameters" element="top:dbReadSelect_newOrderNumberInputParameters"/>
    </wsdl:message>
    <wsdl:message name="PurchaseorderCollection_msg">
        <wsdl:part name="PurchaseorderCollection" element="top:PurchaseorderCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbRead_ptt">
        <wsdl:operation name="dbReadSelect">
            <wsdl:input message="tns:dbReadSelect_inputParameters"/>
            <wsdl:output message="tns:PurchaseorderCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
