<wsdl:definitions
     name="ProcessPurchasedbReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProcessPurchaseOrder/ProcessPurchaseOrder/ProcessPurchasedbReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProcessPurchaseOrder/ProcessPurchaseOrder/ProcessPurchasedbReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ProcessPurchasedbReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ProcessPurchasedbReference_plt" >
    <plt:role name="ProcessPurchasedbReference_role" >
      <plt:portType name="tns:ProcessPurchasedbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ProcessPurchasedbReference" schemaLocation="../Schemas/ProcessPurchasedbReference_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="PurchaseorderCollection_msg">
        <wsdl:part name="PurchaseorderCollection" element="top:PurchaseorderCollection"/>
    </wsdl:message>
    <wsdl:portType name="ProcessPurchasedbReference_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:PurchaseorderCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
