package flexagon.fusion.hrdemo.model.views;

import flexagon.fusion.hrdemo.model.entities.CountriesEOImpl;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 20 17:26:04 CDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CountriesDefaultVORowImpl
  extends ViewRowImpl
{


  public static final int ENTITY_COUNTRIESEO = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    CountryId,
    CountryName,
    RegionId,
    Locations;
    static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int COUNTRYID = AttributesEnum.CountryId.index();
  public static final int COUNTRYNAME = AttributesEnum.CountryName.index();
  public static final int REGIONID = AttributesEnum.RegionId.index();
  public static final int LOCATIONS = AttributesEnum.Locations.index();

  /**
   * This is the default constructor (do not remove).
   */
  public CountriesDefaultVORowImpl()
  {
  }

  /**
   * Gets CountriesEO entity object.
   * @return the CountriesEO
   */
  public CountriesEOImpl getCountriesEO()
  {
    return (CountriesEOImpl) getEntity(ENTITY_COUNTRIESEO);
  }

  /**
   * Gets the attribute value for COUNTRY_ID using the alias name CountryId.
   * @return the COUNTRY_ID
   */
  public String getCountryId()
  {
    return (String) getAttributeInternal(COUNTRYID);
  }

  /**
   * Sets <code>value</code> as attribute value for COUNTRY_ID using the alias name CountryId.
   * @param value value to set the COUNTRY_ID
   */
  public void setCountryId(String value)
  {
    setAttributeInternal(COUNTRYID, value);
  }

  /**
   * Gets the attribute value for COUNTRY_NAME using the alias name CountryName.
   * @return the COUNTRY_NAME
   */
  public String getCountryName()
  {
    return (String) getAttributeInternal(COUNTRYNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for COUNTRY_NAME using the alias name CountryName.
   * @param value value to set the COUNTRY_NAME
   */
  public void setCountryName(String value)
  {
    setAttributeInternal(COUNTRYNAME, value);
  }

  /**
   * Gets the attribute value for REGION_ID using the alias name RegionId.
   * @return the REGION_ID
   */
  public BigDecimal getRegionId()
  {
    return (BigDecimal) getAttributeInternal(REGIONID);
  }

  /**
   * Sets <code>value</code> as attribute value for REGION_ID using the alias name RegionId.
   * @param value value to set the REGION_ID
   */
  public void setRegionId(BigDecimal value)
  {
    setAttributeInternal(REGIONID, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link Locations.
   */
  public RowIterator getLocations()
  {
    return (RowIterator) getAttributeInternal(LOCATIONS);
  }
}

