package flexagon.fusion.hrdemo.model.views;

import flexagon.fusion.hrdemo.model.entities.JobHistoryEOImpl;

import java.sql.Timestamp;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 20 17:26:05 CDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobHistoryDefaultVORowImpl
  extends ViewRowImpl
{


  public static final int ENTITY_JOBHISTORYEO = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    EmployeeId,
    StartDate,
    EndDate,
    JobId,
    DepartmentId;
    static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
  public static final int STARTDATE = AttributesEnum.StartDate.index();
  public static final int ENDDATE = AttributesEnum.EndDate.index();
  public static final int JOBID = AttributesEnum.JobId.index();
  public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();

  /**
   * This is the default constructor (do not remove).
   */
  public JobHistoryDefaultVORowImpl()
  {
  }

  /**
   * Gets JobHistoryEO entity object.
   * @return the JobHistoryEO
   */
  public JobHistoryEOImpl getJobHistoryEO()
  {
    return (JobHistoryEOImpl) getEntity(ENTITY_JOBHISTORYEO);
  }

  /**
   * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId.
   * @return the EMPLOYEE_ID
   */
  public Integer getEmployeeId()
  {
    return (Integer) getAttributeInternal(EMPLOYEEID);
  }

  /**
   * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId.
   * @param value value to set the EMPLOYEE_ID
   */
  public void setEmployeeId(Integer value)
  {
    setAttributeInternal(EMPLOYEEID, value);
  }

  /**
   * Gets the attribute value for START_DATE using the alias name StartDate.
   * @return the START_DATE
   */
  public Timestamp getStartDate()
  {
    return (Timestamp) getAttributeInternal(STARTDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
   * @param value value to set the START_DATE
   */
  public void setStartDate(Timestamp value)
  {
    setAttributeInternal(STARTDATE, value);
  }

  /**
   * Gets the attribute value for END_DATE using the alias name EndDate.
   * @return the END_DATE
   */
  public Timestamp getEndDate()
  {
    return (Timestamp) getAttributeInternal(ENDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
   * @param value value to set the END_DATE
   */
  public void setEndDate(Timestamp value)
  {
    setAttributeInternal(ENDDATE, value);
  }

  /**
   * Gets the attribute value for JOB_ID using the alias name JobId.
   * @return the JOB_ID
   */
  public String getJobId()
  {
    return (String) getAttributeInternal(JOBID);
  }

  /**
   * Sets <code>value</code> as attribute value for JOB_ID using the alias name JobId.
   * @param value value to set the JOB_ID
   */
  public void setJobId(String value)
  {
    setAttributeInternal(JOBID, value);
  }

  /**
   * Gets the attribute value for DEPARTMENT_ID using the alias name DepartmentId.
   * @return the DEPARTMENT_ID
   */
  public Integer getDepartmentId()
  {
    return (Integer) getAttributeInternal(DEPARTMENTID);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name DepartmentId.
   * @param value value to set the DEPARTMENT_ID
   */
  public void setDepartmentId(Integer value)
  {
    setAttributeInternal(DEPARTMENTID, value);
  }
}

