package flexagon.fusion.hrdemo.model.appmodules;

import flexagon.fusion.hrdemo.model.views.DepartmentsDefaultVOImpl;
import flexagon.fusion.hrdemo.model.views.EmployeesDefaultVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------a
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 20 17:27:41 CDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRUIAMImpl
  extends ApplicationModuleImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public HRUIAMImpl()
  {
  }

  /**
   * Container's getter for Employees.
   * @return Employees
   */
  public EmployeesDefaultVOImpl getEmployees()
  {
    return (EmployeesDefaultVOImpl) findViewObject("Employees");
  }

  /**
   * Container's getter for Departments.
   * @return Departments
   */
  public DepartmentsDefaultVOImpl getDepartments()
  {
    return (DepartmentsDefaultVOImpl) findViewObject("Departments");
  }
}

