package flexagon.fusion.hrdemo.model.appmodules;

import oracle.jbo.server.ApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 20 17:27:41 CDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRUIAMDefImpl
  extends ApplicationModuleDefImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public HRUIAMDefImpl()
  {
  }
}

