<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/ReceiveOrdersReadyForShipment"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://www.oracle.com/soasample"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns xp20 xref mhdr oraext dvm socket"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/e2e-1201-composites-templates/FulfillOrder/ReceiveOrdersReadyForShipment"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/ReceiveOrdersReadyForShipment.wsdl"/>
                <oracle-xsl-mapper:rootElement name="E2E1201_OrdersCollection"
                                               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ReceiveOrdersReadyForShipment"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/CanonicalOrder.xsd"/>
                <oracle-xsl-mapper:rootElement name="Order" namespace="http://www.oracle.com/soasample"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.2.0.0(XSLT Build 130323.0142.4249) AT [MON APR 15 06:17:14 PDT 2013].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:Order>
            <tns:OrderNumber>
                <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:orderNumber"/>
            </tns:OrderNumber>
            <tns:OrderDate>
                <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:orderDate"/>
            </tns:OrderDate>
            <tns:Billing>
                <tns:CardPaymentType>
                    <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:cardpaymenttype"/>
                </tns:CardPaymentType>
                <tns:CardNum>
                    <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:cardnum"/>
                </tns:CardNum>
                <tns:ExpireDate>
                    <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:expiredate"/>
                </tns:ExpireDate>
                <tns:CardName>
                    <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:cardname"/>
                </tns:CardName>
                <tns:BillingAddress>
                    <tns:FirstName>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:addressId/ns0:firstName"/>
                    </tns:FirstName>
                    <tns:LastName>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:addressId/ns0:lastName"/>
                    </tns:LastName>
                    <tns:AddressLine>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:addressId/ns0:addressLine1"/>
                    </tns:AddressLine>
                    <xsl:if test="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:addressId/ns0:addressLine2">
                        <tns:AddressLine>
                            <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:addressId/ns0:addressLine2"/>
                        </tns:AddressLine>
                    </xsl:if>
                    <tns:City>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:addressId/ns0:city"/>
                    </tns:City>
                    <tns:State>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:addressId/ns0:state"/>
                    </tns:State>
                    <tns:ZipCode>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:addressId/ns0:zipCode"/>
                    </tns:ZipCode>
                    <tns:PhoneNumber>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:addressId/ns0:phone"/>
                    </tns:PhoneNumber>
                </tns:BillingAddress>
                <tns:AuthorizationDate>
                    <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_BillinginfoCollection/ns0:E2E1201_Billinginfo/ns0:authorizationdate"/>
                </tns:AuthorizationDate>
            </tns:Billing>
            <tns:Shipping>
                <tns:Address>
                    <tns:FirstName>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_ShippinginfoCollection/ns0:E2E1201_Shippinginfo/ns0:addressId/ns0:firstName"/>
                    </tns:FirstName>
                    <tns:LastName>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_ShippinginfoCollection/ns0:E2E1201_Shippinginfo/ns0:addressId/ns0:lastName"/>
                    </tns:LastName>
                    <tns:AddressLine>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_ShippinginfoCollection/ns0:E2E1201_Shippinginfo/ns0:addressId/ns0:addressLine1"/>
                    </tns:AddressLine>
                    <xsl:if test="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_ShippinginfoCollection/ns0:E2E1201_Shippinginfo/ns0:addressId/ns0:addressLine2">
                        <tns:AddressLine>
                            <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_ShippinginfoCollection/ns0:E2E1201_Shippinginfo/ns0:addressId/ns0:addressLine2"/>
                        </tns:AddressLine>
                    </xsl:if>
                    <tns:City>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_ShippinginfoCollection/ns0:E2E1201_Shippinginfo/ns0:addressId/ns0:city"/>
                    </tns:City>
                    <tns:State>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_ShippinginfoCollection/ns0:E2E1201_Shippinginfo/ns0:addressId/ns0:state"/>
                    </tns:State>
                    <tns:ZipCode>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_ShippinginfoCollection/ns0:E2E1201_Shippinginfo/ns0:addressId/ns0:zipCode"/>
                    </tns:ZipCode>
                    <tns:PhoneNumber>
                        <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_ShippinginfoCollection/ns0:E2E1201_Shippinginfo/ns0:addressId/ns0:phone"/>
                    </tns:PhoneNumber>
                </tns:Address>
                <tns:ShippingSpeed>
                    <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_ShippinginfoCollection/ns0:E2E1201_Shippinginfo/ns0:shipspeed"/>
                </tns:ShippingSpeed>
            </tns:Shipping>
            <tns:Email>
                <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:email"/>
            </tns:Email>
            <tns:Items>
                <xsl:for-each select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:e2E1201_OrderItemsCollection/ns0:E2E1201_OrderItems">
                    <tns:Item>
                        <tns:SKU>
                            <xsl:value-of select="ns0:sku"/>
                        </tns:SKU>
                        <tns:Quantity>
                            <xsl:value-of select="ns0:quantity"/>
                        </tns:Quantity>
                        <tns:UnitPrice>
                            <xsl:value-of select="ns0:unitprice"/>
                        </tns:UnitPrice>
                        <tns:Brand>
                            <xsl:value-of select="ns0:brand"/>
                        </tns:Brand>
                        <tns:Model>
                            <xsl:value-of select="ns0:model"/>
                        </tns:Model>
                        <tns:Category>
                            <xsl:value-of select="ns0:categoryId"/>
                        </tns:Category>
                        <tns:Description>
                            <xsl:value-of select="ns0:description"/>
                        </tns:Description>
                    </tns:Item>
                </xsl:for-each>
            </tns:Items>
            <tns:Status>
                <xsl:value-of select="/ns0:E2E1201_OrdersCollection/ns0:E2E1201_Orders/ns0:status"/>
            </tns:Status>
        </tns:Order>
    </xsl:template>
</xsl:stylesheet>
