<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ValidatePayment"
     targetNamespace="http://oracle.com/sca/soapservice/e2e-1201-composites/ValidatePayment/ValidatePayment"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://oracle.com/sca/soapservice/e2e-1201-composites/ValidatePayment/ValidatePayment"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ValidatePayment">
        <plnk:role name="validatePaymentPortType" portType="tns:validatePaymentPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://oracle.com/sca/soapservice/e2e-1201-composites/ValidatePayment/ValidatePayment"
         location="ValidatePayment.wsdl"/>
</wsdl:definitions>
