<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.oracle.com/ValidatePayment"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:WL5G3N2="http://www.oracle.com/ValidatePayment"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="validatePayment">
        <plnk:role name="validatePaymentPortType" portType="WL5G3N2:validatePaymentPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.oracle.com/ValidatePayment" location="ValidatePS.wsdl"/>
</wsdl:definitions>
