CREATE USER FD IDENTIFIED BY &1 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER FD QUOTA UNLIMITED ON USERS;

CREATE USER FD_ADMIN IDENTIFIED BY &1 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER FD_ADMIN QUOTA UNLIMITED ON USERS;

grant all privileges on FF.DB_PROPERTIES to FD;
grant all privileges on FF.DB_PROPERTIES_DATA to FD;
