grant CREATE SESSION to FD_ADMIN;

grant all privileges on FF.DB_PROPERTIES to FD;
grant all privileges on FF.DB_PROPERTIES_DATA to FD;

grant all privileges on FD.ARC_FOLDER_PROJECT_VERSION to FD_ADMIN;
grant all privileges on FD.ARC_FOLDER_REQUEST to FD_ADMIN;
grant all privileges on FD.ARC_FOLDER_VERSION to FD_ADMIN;
grant all privileges on FD.ARC_HUMAN_TASK to FD_ADMIN;
grant all privileges on FD.ARC_PACKAGE_OBJECT_EXECUTION to FD_ADMIN;
grant all privileges on FD.ARC_PACKAGE_OBJECT to FD_ADMIN;
grant all privileges on FD.ARC_PLUGIN_EXECUTION to FD_ADMIN;
grant all privileges on FD.ARC_PLUGIN_EXECUTION_LOG to FD_ADMIN;
grant all privileges on FD.ARC_PLUGIN_EXECUTION_OUTPUT to FD_ADMIN;
grant all privileges on FD.ARC_PLUGIN_EXEC_OUTPUT_VALUE to FD_ADMIN;
grant all privileges on FD.ARC_PROJECT_VERSION to FD_ADMIN;
grant all privileges on FD.ARC_PROJECT_VERSION_DATA to FD_ADMIN;
grant all privileges on FD.ARC_PROJECT_VERSION_DATA_VAL to FD_ADMIN;
grant all privileges on FD.ARC_SCHEDULED_TASK to FD_ADMIN;
grant all privileges on FD.ARC_TEST_DEFINITION_RUN to FD_ADMIN;
grant all privileges on FD.ARC_TEST_DEF_QUAL_VALUE to FD_ADMIN;
grant all privileges on FD.ARC_TEST_RESULT to FD_ADMIN;
grant all privileges on FD.ARC_TEST_RUN to FD_ADMIN;
grant all privileges on FD.ARC_TEST_SET_QUALIFIER_VALUE to FD_ADMIN;
grant all privileges on FD.ARC_TEST_SET_RUN to FD_ADMIN;
grant all privileges on FD.ARC_WORKFLOW_EXECUTION to FD_ADMIN;
grant all privileges on FD.ARC_WORKFLOW_EXECUTION_DATA to FD_ADMIN;
grant all privileges on FD.ARC_WORKFLOW_REQUEST to FD_ADMIN;
grant all privileges on FD.ARC_WORKFLOW_REQUEST_INPUT to FD_ADMIN;
grant all privileges on FD.ARC_WORKFLOW_REQUEST_INST to FD_ADMIN;
grant all privileges on FD.DEPLOY_APPROVAL to FD_ADMIN;
grant all privileges on FD.DEPLOY_APPROVAL_GROUP to FD_ADMIN;
grant all privileges on FD.DEPLOY_WINDOW to FD_ADMIN;
grant all privileges on FD.DEPLOY_WINDOW_APPROVAL_GROUP to FD_ADMIN;
grant all privileges on FD.ENDPOINT to FD_ADMIN;
grant all privileges on FD.ENVIRONMENT to FD_ADMIN;
grant all privileges on FD.ENVIRONMENT_INSTANCE to FD_ADMIN;
grant all privileges on FD.ENV_INST_ENDPOINT to FD_ADMIN;
grant all privileges on FD.ENV_INST_ENDPOINT_RSC_TYPE to FD_ADMIN;
grant all privileges on FD.FD_FLEXDEPLOY_VERSION to FD_ADMIN;
grant all privileges on FD.FD_GROUP to FD_ADMIN;
grant all privileges on FD.FD_GROUP_PERMISSION to FD_ADMIN;
grant all privileges on FD.FD_PERMISSION to FD_ADMIN;
grant all privileges on FD.FD_REALM to FD_ADMIN;
grant all privileges on FD.FD_USER to FD_ADMIN;
grant all privileges on FD.FD_USER_ATTRIBUTE to FD_ADMIN;
grant all privileges on FD.FD_USER_ATTR_DEF to FD_ADMIN;
grant all privileges on FD.FD_USER_GROUP to FD_ADMIN;
grant all privileges on FD.FLEX_FIELD_METADATA to FD_ADMIN;
grant all privileges on FD.FOLDER to FD_ADMIN;
grant all privileges on FD.FOLDER_PROJECT_VERSION to FD_ADMIN;
grant all privileges on FD.FOLDER_REQUEST to FD_ADMIN;
grant all privileges on FD.FOLDER_REQUEST_CURRENT_STATE to FD_ADMIN;
grant all privileges on FD.FOLDER_VERSION to FD_ADMIN;
grant all privileges on FD.HUMAN_TASK to FD_ADMIN;
grant all privileges on FD.INSTANCE to FD_ADMIN;
grant all privileges on FD.INST_PROPERTY_SET to FD_ADMIN;
grant all privileges on FD.LICENSE_INFO to FD_ADMIN;
grant all privileges on FD.NOTIFICATION to FD_ADMIN;
grant all privileges on FD.NOTIFICATION_EVENT to FD_ADMIN;
grant all privileges on FD.NOTIFICATION_RECIPIENT to FD_ADMIN;
grant all privileges on FD.PLUGIN to FD_ADMIN;
grant all privileges on FD.PLUGIN_EXECUTION to FD_ADMIN;
grant all privileges on FD.PLUGIN_EXECUTION_LOG to FD_ADMIN;
grant all privileges on FD.PLUGIN_EXECUTION_OUTPUT to FD_ADMIN;
grant all privileges on FD.PLUGIN_EXECUTION_OUTPUT_VALUE to FD_ADMIN;
grant all privileges on FD.PLUGIN_VERSION to FD_ADMIN;
grant all privileges on FD.PLUGIN_VERSION_DATA to FD_ADMIN;
grant all privileges on FD.PLUGIN_VERSION_JAR to FD_ADMIN;
grant all privileges on FD.PROJECT to FD_ADMIN;
grant all privileges on FD.PROJECT_CONFIG to FD_ADMIN;
grant all privileges on FD.PROJECT_CONFIG_VALUE to FD_ADMIN;
grant all privileges on FD.PROJECT_STREAM to FD_ADMIN;
grant all privileges on FD.PROJECT_STREAM_TEST_DEF to FD_ADMIN;
grant all privileges on FD.PROJECT_TEST_TYPE to FD_ADMIN;
grant all privileges on FD.PROJECT_TRIGGER to FD_ADMIN;
grant all privileges on FD.PROJECT_TRIGGER_CONFIG to FD_ADMIN;
grant all privileges on FD.PROJECT_VERSION to FD_ADMIN;
grant all privileges on FD.PROJECT_VERSION_DATA to FD_ADMIN;
grant all privileges on FD.PROJECT_VERSION_DATA_VAL to FD_ADMIN;
grant all privileges on FD.PROJECT_WF_CURRENT_STATUS to FD_ADMIN;
grant all privileges on FD.PROJECT_WORKFLOW to FD_ADMIN;
grant all privileges on FD.PROJECT_WORKFLOW_INSTANCE to FD_ADMIN;
grant all privileges on FD.PROPERTY_KEY to FD_ADMIN;
grant all privileges on FD.PROPERTY_KEY_DEFINITION to FD_ADMIN;
grant all privileges on FD.PROPERTY_SET to FD_ADMIN;
grant all privileges on FD.PROPERTY_SET_KEY_DEF to FD_ADMIN;
grant all privileges on FD.PROPERTY_VALUE to FD_ADMIN;
grant all privileges on FD.PURGE_FOLDER_VERSION_KEY to FD_ADMIN;
grant all privileges on FD.PURGE_PKG_VERSION_KEY to FD_ADMIN;
grant all privileges on FD.PURGE_PROJ_VERSION_KEY to FD_ADMIN;
grant all privileges on FD.RESOURCE_TYPE to FD_ADMIN;
grant all privileges on FD.SCHEDULED_TASK to FD_ADMIN;
grant all privileges on FD.TEMPLATE to FD_ADMIN;
grant all privileges on FD.TEMPLATE_DATA to FD_ADMIN;
grant all privileges on FD.TEMPLATE_INPUT to FD_ADMIN;
grant all privileges on FD.TESTING_TOOL to FD_ADMIN;
grant all privileges on FD.TEST_DEFINITION to FD_ADMIN;
grant all privileges on FD.TEST_DEFINITION_INPUT to FD_ADMIN;
grant all privileges on FD.TEST_DEFINITION_QUALIFIER to FD_ADMIN;
grant all privileges on FD.TEST_DEFINITION_RUN to FD_ADMIN;
grant all privileges on FD.TEST_DEF_QUALIFIER_VALUE to FD_ADMIN;
grant all privileges on FD.TEST_QUALIFIER to FD_ADMIN;
grant all privileges on FD.TEST_RESULT to FD_ADMIN;
grant all privileges on FD.TEST_RUN to FD_ADMIN;
grant all privileges on FD.TEST_SET to FD_ADMIN;
grant all privileges on FD.TEST_SET_QUALIFIER to FD_ADMIN;
grant all privileges on FD.TEST_SET_QUALIFIER_VALUE to FD_ADMIN;
grant all privileges on FD.TEST_SET_RUN to FD_ADMIN;
grant all privileges on FD.TEST_TYPE to FD_ADMIN;
grant all privileges on FD.WORKFLOW to FD_ADMIN;
grant all privileges on FD.WORKFLOW_EXECUTION to FD_ADMIN;
grant all privileges on FD.WORKFLOW_EXECUTION_DATA to FD_ADMIN;
grant all privileges on FD.WORKFLOW_REQUEST to FD_ADMIN;
grant all privileges on FD.WORKFLOW_REQUEST_INPUT to FD_ADMIN;
grant all privileges on FD.WORKFLOW_REQUEST_INST to FD_ADMIN;
grant all privileges on FD.WORKFLOW_VERSION to FD_ADMIN;
grant all privileges on FD.WORKFLOW_VERSION_DATA to FD_ADMIN;
grant all privileges on FD.FD_REALM_GROUP to FD_ADMIN;
grant all privileges on FD.FD_REALM_GROUP_MAP to FD_ADMIN;

grant execute on fd.flex_archive_purge_delete to fd_admin;
grant execute on fd.flex_archive_purge_identify to fd_admin;
grant execute on fd.flex_purge_archive to fd_admin;
grant execute on fd.flex_purge_identify to fd_admin;
grant execute on fd.flex_purge_operational_delete to fd_admin;

grant SELECT on "FD"."VAPPLICATIONSTATISTICS" to "FD_ADMIN" ;
grant SELECT on "FD"."VTESTAUTOMATIONRESULT" to "FD_ADMIN" ;
grant SELECT on "FD"."VCURRENTPROJECTTASK" to "FD_ADMIN" ;
grant SELECT on "FD"."VPROJECTTASKTIMELINE" to "FD_ADMIN" ;

grant all privileges on FD.ISSUETRACKINGSYSTEM to FD_ADMIN;
grant all privileges on FD.PROJECT_ITS_CONFIG to FD_ADMIN;

grant all privileges on FD.OBJECT_ATTRIBUTE_DEF to FD_ADMIN;
grant all privileges on FD.OBJECT_TYPE to FD_ADMIN;

grant all privileges on FD.PACKAGE_OBJECT to FD_ADMIN;
grant all privileges on FD.PACKAGE_OBJECT_EXECUTION to FD_ADMIN;
grant all privileges on FD.PACKAGE_OBJ_CURRENT_STATUS to FD_ADMIN;
grant all privileges on FD.PROJECT_OBJECT to FD_ADMIN;
grant all privileges on FD.PROJECT_OBJECT_ATTRIBUTE to FD_ADMIN;
grant all privileges on FD.PROJECT_OBJECT_ATTRIBUTE_VAL to FD_ADMIN;

grant all privileges on FD.ITSStatus to FD_ADMIN;
grant all privileges on FD.PROJECT_ENV_ITS_CONFIG to FD_ADMIN;

grant all privileges on FD.VPROJECTTASKTIMELINEALL to FD_ADMIN;
grant all privileges on FD.ENVIRONMENT_ITS_CONFIG to FD_ADMIN;