CREATE TABLE FF.DB_PROPERTIES 
( 
  DB_PROPERTIES_ID NUMERIC(20, 0) NOT NULL 
, DB_PROPERTIES_NAME VARCHAR(255) NOT NULL 
, DB_PROPERTIES_KEY VARCHAR(255) NOT NULL 
, SEQUENCE_NUMBER NUMERIC(8, 0) NULL 
, DESCRIPTION VARCHAR(255) NULL 
, IS_ACTIVE CHAR(1) NOT NULL 
, IS_REQUIRED CHAR(1) NOT NULL 
, IS_ENCRYPTED CHAR(1) NOT NULL 
, DATA_TYPE VARCHAR(255) NOT NULL 
, VALIDATION_SCRIPT VARCHAR(4000) NULL 
, VALIDATION_MESSAGE VARCHAR(4000) NULL 
, MIN_VALUE NUMERIC(20, 0) NULL 
, MAX_VALUE NUMERIC(20, 0) NULL 
, DISPLAY_ROWS NUMERIC(8, 0) NULL 
, DISPLAY_COLUMNS NUMERIC(8,0) NULL 
, LIST_DATA VARCHAR(4000) NULL 
, CREATED_ON TIMESTAMP NOT NULL 
, CREATED_BY VARCHAR(128) NOT NULL 
, UPDATED_ON TIMESTAMP NOT NULL 
, UPDATED_BY VARCHAR(128) NOT NULL 
, VERSION_NUMBER NUMERIC(8, 0) NULL 
, CONSTRAINT DB_PROPERTIES_PK PRIMARY KEY ( DB_PROPERTIES_ID )
, CONSTRAINT DB_PROPERTIES_UK1 UNIQUE ( DB_PROPERTIES_NAME, DB_PROPERTIES_KEY ) );

CREATE TABLE FF.DB_PROPERTIES_DATA 
( 
  DB_PROPERTIES_DATA_ID NUMERIC(20, 0) NOT NULL 
, DB_PROPERTIES_ID NUMERIC(20, 0) NOT NULL 
, SEQUENCE_NUMBER NUMERIC(8, 0) NOT NULL 
, DB_PROPERTIES_VALUE VARCHAR(4000) NOT NULL 
, DESCRIPTION VARCHAR(255) NULL 
, IS_ACTIVE CHAR(1) NOT NULL 
, CREATED_ON TIMESTAMP NOT NULL 
, CREATED_BY VARCHAR(128) NOT NULL 
, UPDATED_ON TIMESTAMP NOT NULL 
, UPDATED_BY VARCHAR(128) NOT NULL 
, VERSION_NUMBER NUMERIC(8, 0) NULL 
, CONSTRAINT DB_PROPERTIES_DATA_PK PRIMARY KEY ( DB_PROPERTIES_DATA_ID )
, CONSTRAINT DB_PROPERTIES_DATA_UK1 UNIQUE ( DB_PROPERTIES_DATA_ID, SEQUENCE_NUMBER ) );

CREATE TABLE FF.LIST 
( 
  LIST_CODE_ID NUMERIC(20, 0) NOT NULL 
, LIST_NAME VARCHAR(255) NOT NULL 
, LIST_CODE VARCHAR(50) NOT NULL 
, FLEX_FIELD_1 VARCHAR(255) NULL 
, FLEX_FIELD_2 VARCHAR(255) NULL 
, FLEX_FIELD_3 VARCHAR(255) NULL 
, FLEX_FIELD_4 VARCHAR(255) NULL 
, FLEX_FIELD_5 VARCHAR(255) NULL 
, FLEX_FIELD_6 VARCHAR(255) NULL 
, FLEX_FIELD_7 VARCHAR(255) NULL 
, FLEX_FIELD_8 VARCHAR(255) NULL 
, FLEX_FIELD_9 VARCHAR(255) NULL 
, FLEX_FIELD_10 VARCHAR(255) NULL 
, CREATED_ON TIMESTAMP NOT NULL 
, CREATED_BY VARCHAR(128) NOT NULL 
, UPDATED_ON TIMESTAMP NOT NULL 
, UPDATED_BY VARCHAR(128) NOT NULL 
, VERSION_NUMBER NUMERIC(8, 0) NULL 
, CONSTRAINT LIST_PK PRIMARY KEY ( LIST_CODE_ID )
, CONSTRAINT LIST_UK1 UNIQUE ( LIST_NAME, LIST_CODE ) );

CREATE TABLE FF.LIST_DISPLAY_DATA 
( 
  LIST_DISPLAY_DATA_ID NUMERIC(20, 0) NOT NULL 
, LIST_NAME VARCHAR(255) NOT NULL 
, LIST_CODE VARCHAR(50) NOT NULL 
, LANGUAGE VARCHAR(5) NULL 
, COUNTRY VARCHAR(5) NULL 
, VARIANT VARCHAR(50) NULL 
, SHORT_DISPLAY_TEXT VARCHAR(255) NOT NULL 
, LONG_DISPLAY_TEXT VARCHAR(255) NOT NULL 
, CREATED_ON TIMESTAMP NOT NULL 
, CREATED_BY VARCHAR(128) NOT NULL 
, UPDATED_ON TIMESTAMP NOT NULL 
, UPDATED_BY VARCHAR(128) NOT NULL 
, VERSION_NUMBER NUMERIC(8, 0) NULL 
, CONSTRAINT LIST_DISPLAY_DATA_PK PRIMARY KEY ( LIST_DISPLAY_DATA_ID )
, CONSTRAINT LIST_DISPLAY_DATA_UK1 UNIQUE ( LIST_NAME, LIST_CODE, LANGUAGE, COUNTRY, VARIANT ) );

CREATE TABLE FF.LIST_FILTER_DATA 
( 
  LIST_FILTER_DATA_ID NUMERIC(20, 0) NOT NULL 
, FILTER_NAME VARCHAR(50) NOT NULL 
, FILTER_BY_LIST_NAME VARCHAR(255) NULL 
, FILTER_BY_LIST_CODE VARCHAR(50) NULL 
, FILTERED_LIST_NAME VARCHAR(255) NOT NULL 
, FILTERED_LIST_CODE VARCHAR(50) NOT NULL 
, CREATED_ON TIMESTAMP NOT NULL 
, CREATED_BY VARCHAR(128) NOT NULL 
, UPDATED_ON TIMESTAMP NOT NULL 
, UPDATED_BY VARCHAR(128) NOT NULL 
, VERSION_NUMBER NUMERIC(8, 0) NULL 
, CONSTRAINT LIST_FILTER_PK PRIMARY KEY ( LIST_FILTER_DATA_ID )
, CONSTRAINT LIST_FILTER_DATA_UK1 UNIQUE ( FILTER_NAME, FILTER_BY_LIST_NAME, FILTER_BY_LIST_CODE, FILTERED_LIST_NAME, FILTERED_LIST_CODE ) );

CREATE TABLE FF.RESOURCE_LOCK 
( 
  RESOURCE_TYPE VARCHAR(255) NOT NULL 
, RESOURCE_IDENTITY VARCHAR(255) NOT NULL 
, LOCK_OWNER_TYPE VARCHAR(255) NOT NULL 
, LOCK_OWNER_ID NUMERIC(20, 0) NOT NULL 
, CREATED_ON TIMESTAMP NOT NULL 
, CREATED_BY VARCHAR(128) NOT NULL 
, UPDATED_ON TIMESTAMP NOT NULL 
, UPDATED_BY VARCHAR(128) NOT NULL 
, VERSION_NUMBER NUMERIC(8, 0) NULL 
, CONSTRAINT RESOURCE_LOCK_PK PRIMARY KEY ( RESOURCE_TYPE, RESOURCE_IDENTITY ) );

CREATE TABLE FF.SEQUENCE_BLOCK 
( 
  SEQ_NAM VARCHAR(50) NOT NULL 
, NEXT_VALUE NUMERIC(20, 0) NOT NULL 
, BLOCK_SIZE NUMERIC(20, 0) NOT NULL 
, RESET_VALUE NUMERIC(20, 0) NOT NULL 
, MAX_VALUE NUMERIC(20, 0) NOT NULL 
, CREATED_ON TIMESTAMP NOT NULL 
, CREATED_BY VARCHAR(128) NOT NULL 
, UPDATED_ON TIMESTAMP NOT NULL 
, UPDATED_BY VARCHAR(128) NOT NULL 
, VERSION_NUMBER NUMERIC(8, 0) NULL 
, CONSTRAINT SEQUENCE_BLOCK_PK PRIMARY KEY ( SEQ_NAM ) );

ALTER TABLE FF.DB_PROPERTIES_DATA ADD CONSTRAINT DB_PROPERTIES_DATA FOREIGN KEY ( DB_PROPERTIES_ID )
 REFERENCES FF.DB_PROPERTIES ( DB_PROPERTIES_ID );

ALTER TABLE FF.LIST_DISPLAY_DATA ADD CONSTRAINT LIST_DISPLAY_DATA FOREIGN KEY ( LIST_NAME, LIST_CODE )
 REFERENCES FF.LIST ( LIST_NAME,  LIST_CODE );

ALTER TABLE FF.LIST_FILTER_DATA ADD CONSTRAINT LIST_FILTERS FOREIGN KEY ( FILTER_BY_LIST_NAME, FILTER_BY_LIST_CODE )
 REFERENCES FF.LIST ( LIST_NAME,  LIST_CODE );

ALTER TABLE FF.LIST_FILTER_DATA ADD CONSTRAINT LIST_FILTER_DATA_FK1 FOREIGN KEY ( FILTERED_LIST_NAME, FILTERED_LIST_CODE )
 REFERENCES FF.LIST ( LIST_NAME,  LIST_CODE );
 
CREATE INDEX FFIX1 ON FF.LIST_FILTER_DATA(FILTER_BY_LIST_NAME);
CREATE INDEX FFIX2 ON FF.LIST_FILTER_DATA(FILTERED_LIST_NAME);

CREATE INDEX FF.FFDPDIX1 ON FF.DB_PROPERTIES_DATA (DB_PROPERTIES_ID) 
  COMPUTE STATISTICS ;
CREATE INDEX FF.FFLFDIX1 ON FF.LIST_FILTER_DATA (FILTER_BY_LIST_NAME, FILTER_BY_LIST_CODE) 
  COMPUTE STATISTICS ;
CREATE INDEX FF.FFLFDIX2 ON FF.LIST_FILTER_DATA (FILTERED_LIST_NAME, FILTERED_LIST_CODE) 
  COMPUTE STATISTICS ;