delete from FF.LIST_FILTER_DATA;
delete from FF.LIST_DISPLAY_DATA;
delete from FF.LIST;

-- Property Set Owner Type
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (101, 'PROPERTY_SET_OWNER_TYPE', 'PLUGIN', sysdate, 'anonymous', sysdate, 'anonymous', 1);
--INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
--VALUES (102, 'PROPERTY_SET_OWNER_TYPE', 'TECHNOLOGY', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (103, 'PROPERTY_SET_OWNER_TYPE', 'WORKFLOW', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (104, 'PROPERTY_SET_OWNER_TYPE', 'TESTING_TOOL', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (101, 'PROPERTY_SET_OWNER_TYPE', 'PLUGIN', 'PLUGIN', 'Plugin', sysdate, 'anonymous', sysdate,'anonymous', 1);
--INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
--VALUES (102, 'PROPERTY_SET_OWNER_TYPE', 'TECHNOLOGY', 'TECHNOLOGY', 'Technology', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (103, 'PROPERTY_SET_OWNER_TYPE', 'WORKFLOW', 'WORKFLOW', 'Workflow', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (104, 'PROPERTY_SET_OWNER_TYPE', 'TESTING_TOOL', 'TESTING_TOOL', 'Testing Tool', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (101, 'FD', 'PROPERTY_SET_OWNER_TYPE', 'PLUGIN', sysdate, 'anonymous', sysdate, 'anonymous', 1);
--INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
--VALUES (102, 'FD', 'PROPERTY_SET_OWNER_TYPE', 'TECHNOLOGY', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (103, 'FD', 'PROPERTY_SET_OWNER_TYPE', 'WORKFLOW', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (104, 'FD', 'PROPERTY_SET_OWNER_TYPE', 'TESTING_TOOL', sysdate, 'anonymous', sysdate, 'anonymous', 1);


-- Property Key Data Type
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (121, 'PROPERTY_KEY_DATATYPE', 'String', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (122, 'PROPERTY_KEY_DATATYPE', 'Integer', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (123, 'PROPERTY_KEY_DATATYPE', 'Boolean', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (124, 'PROPERTY_KEY_DATATYPE', 'Long', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (125, 'PROPERTY_KEY_DATATYPE', 'Double', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (126, 'PROPERTY_KEY_DATATYPE', 'Float', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (121, 'PROPERTY_KEY_DATATYPE', 'String', 'String', 'String', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (122, 'PROPERTY_KEY_DATATYPE', 'Integer', 'Integer', 'Integer', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (123, 'PROPERTY_KEY_DATATYPE', 'Boolean', 'Boolean', 'Boolean', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (124, 'PROPERTY_KEY_DATATYPE', 'Long', 'Long', 'Long', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (125, 'PROPERTY_KEY_DATATYPE', 'Double', 'Double', 'Double', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (126, 'PROPERTY_KEY_DATATYPE', 'Float', 'Float', 'Float', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (121, 'FD', 'PROPERTY_KEY_DATATYPE', 'String', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (122, 'FD', 'PROPERTY_KEY_DATATYPE', 'Integer', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (123, 'FD', 'PROPERTY_KEY_DATATYPE', 'Boolean', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (124, 'FD', 'PROPERTY_KEY_DATATYPE', 'Long', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (125, 'FD', 'PROPERTY_KEY_DATATYPE', 'Double', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (126, 'FD', 'PROPERTY_KEY_DATATYPE', 'Float', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- 4.0 Changes Added new Filter for Workflow Property Definition UI
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (127, 'FDWF', 'PROPERTY_KEY_DATATYPE', 'String', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (128, 'FDWF', 'PROPERTY_KEY_DATATYPE', 'Integer', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (129, 'FDWF', 'PROPERTY_KEY_DATATYPE', 'Boolean', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (130, 'FDWF', 'PROPERTY_KEY_DATATYPE', 'Double', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Workflow Type
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (301, 'WORKFLOW_TYPE', 'BUILD', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (302, 'WORKFLOW_TYPE', 'DEPLOY', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (303, 'WORKFLOW_TYPE', 'OTHER', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (304, 'WORKFLOW_TYPE', 'TEST_DEFINITION', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (305, 'WORKFLOW_TYPE', 'TEST', sysdate, 'anonymous', sysdate, 'anonymous', 1);


-- UI filter for Workflow Type
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (310, 'FD_UI', 'WORKFLOW_TYPE', 'BUILD', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (311, 'FD_UI', 'WORKFLOW_TYPE', 'DEPLOY', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (312, 'FD_UI', 'WORKFLOW_TYPE', 'OTHER', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (313, 'FD_UI', 'WORKFLOW_TYPE', 'TEST_DEFINITION', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (301, 'WORKFLOW_TYPE', 'BUILD', 'BUILD', 'Build', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (302, 'WORKFLOW_TYPE', 'DEPLOY', 'DEPLOY', 'Deploy', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (303, 'WORKFLOW_TYPE', 'OTHER', 'OTHER', 'Other', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (304, 'WORKFLOW_TYPE', 'TEST', 'TEST', 'Test', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (305, 'WORKFLOW_TYPE', 'TEST_DEFINITION', 'TEST_DEFINITION', 'Test Definition', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (301, 'FD', 'WORKFLOW_TYPE', 'BUILD', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (302, 'FD', 'WORKFLOW_TYPE', 'DEPLOY', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (303, 'FD', 'WORKFLOW_TYPE', 'OTHER', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (304, 'FD', 'WORKFLOW_TYPE', 'TEST', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (305, 'FD', 'WORKFLOW_TYPE', 'TEST_DEFINITION', sysdate, 'anonymous', sysdate, 'anonymous', 1);


-- Property Scope
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (401, 'PROPERTY_SCOPE', 'ENVINST', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (402, 'PROPERTY_SCOPE', 'PROJECT', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (403, 'PROPERTY_SCOPE', 'INST', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (401, 'PROPERTY_SCOPE', 'ENVINST', 'ENVINST', 'Environment Instance', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (402, 'PROPERTY_SCOPE', 'PROJECT', 'PROJECT', 'Project', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (403, 'PROPERTY_SCOPE', 'INST', 'INST', 'Instance', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (401, 'FD', 'PROPERTY_SCOPE', 'ENVINST', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (402, 'FD', 'PROPERTY_SCOPE', 'PROJECT', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (403, 'FD', 'PROPERTY_SCOPE', 'INST', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (411, 'FDWF', 'PROPERTY_SCOPE', 'ENVINST', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (412, 'FDWF', 'PROPERTY_SCOPE', 'PROJECT', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Plugin Execution Status
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (501, 'PLUGIN_EXECUTION_STATUS', 'QUEUED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (502, 'PLUGIN_EXECUTION_STATUS', 'RUNNING', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (503, 'PLUGIN_EXECUTION_STATUS', 'SUCCESSFUL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (504, 'PLUGIN_EXECUTION_STATUS', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (505, 'PLUGIN_EXECUTION_STATUS', 'ABORTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (501, 'PLUGIN_EXECUTION_STATUS', 'QUEUED', 'QUEUED', 'Queued', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (502, 'PLUGIN_EXECUTION_STATUS', 'RUNNING', 'RUNNING', 'Running', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (503, 'PLUGIN_EXECUTION_STATUS', 'SUCCESSFUL', 'SUCCESSFUL', 'Successful', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (504, 'PLUGIN_EXECUTION_STATUS', 'FAILED', 'FAILED', 'Failed', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (505, 'PLUGIN_EXECUTION_STATUS', 'ABORTED', 'ABORTED', 'Aborted', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (501, 'FD', 'PLUGIN_EXECUTION_STATUS', 'QUEUED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (502, 'FD', 'PLUGIN_EXECUTION_STATUS', 'RUNNING', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (503, 'FD', 'PLUGIN_EXECUTION_STATUS', 'SUCCESSFUL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (504, 'FD', 'PLUGIN_EXECUTION_STATUS', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (505, 'FD', 'PLUGIN_EXECUTION_STATUS', 'ABORTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Workflow Execution Status
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (601, 'WORKFLOW_EXECUTION_STATUS', 'Scheduled', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (602, 'WORKFLOW_EXECUTION_STATUS', 'Running', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (603, 'WORKFLOW_EXECUTION_STATUS', 'Success', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (604, 'WORKFLOW_EXECUTION_STATUS', 'Failure', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (605, 'WORKFLOW_EXECUTION_STATUS', 'Queued', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (606, 'WORKFLOW_EXECUTION_STATUS', 'AlreadyDeployed', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (607, 'WORKFLOW_EXECUTION_STATUS', 'Aborted', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (601, 'WORKFLOW_EXECUTION_STATUS', 'Scheduled', 'Scheduled', 'Scheduled', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (602, 'WORKFLOW_EXECUTION_STATUS', 'Running', 'Running', 'Running', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (603, 'WORKFLOW_EXECUTION_STATUS', 'Success', 'Success', 'Success', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (604, 'WORKFLOW_EXECUTION_STATUS', 'Failure', 'Failure', 'Failure', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (605, 'WORKFLOW_EXECUTION_STATUS', 'Queued', 'Queued', 'Queued', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (606, 'WORKFLOW_EXECUTION_STATUS', 'AlreadyDeployed', 'AlreadyDeployed', 'AlreadyDeployed', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (607, 'WORKFLOW_EXECUTION_STATUS', 'Aborted', 'Aborted', 'Aborted', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (601, 'FD', 'WORKFLOW_EXECUTION_STATUS', 'Scheduled', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (602, 'FD', 'WORKFLOW_EXECUTION_STATUS', 'Running', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (603, 'FD', 'WORKFLOW_EXECUTION_STATUS', 'Success', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (604, 'FD', 'WORKFLOW_EXECUTION_STATUS', 'Failure', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (605, 'FD', 'WORKFLOW_EXECUTION_STATUS', 'Queued', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (606, 'FD', 'WORKFLOW_EXECUTION_STATUS', 'AlreadyDeployed', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (620, 'FD', 'WORKFLOW_EXECUTION_STATUS', 'Aborted', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (607, 'FD-REPORT', 'WORKFLOW_EXECUTION_STATUS', 'Scheduled', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (608, 'FD-REPORT', 'WORKFLOW_EXECUTION_STATUS', 'Running', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (609, 'FD-REPORT', 'WORKFLOW_EXECUTION_STATUS', 'Success', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (610, 'FD-REPORT', 'WORKFLOW_EXECUTION_STATUS', 'Failure', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (611, 'FD-REPORT', 'WORKFLOW_EXECUTION_STATUS', 'Queued', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (612, 'FD-REPORT', 'WORKFLOW_EXECUTION_STATUS', 'Aborted', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Property Sub Type
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (701, 'PROPERTY_KEY_SUBDATATYPE', 'URL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (702, 'PROPERTY_KEY_SUBDATATYPE', 'JDBCURL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (703, 'PROPERTY_KEY_SUBDATATYPE', 'DIRECTORY', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (701, 'PROPERTY_KEY_SUBDATATYPE', 'URL', 'URL', 'URL', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (702, 'PROPERTY_KEY_SUBDATATYPE', 'JDBCURL', 'JDBCURL', 'JDBCURL', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (703, 'PROPERTY_KEY_SUBDATATYPE', 'DIRECTORY', 'Directory', 'Directory', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, FILTER_BY_LIST_NAME, FILTER_BY_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (701, 'FD', 'PROPERTY_KEY_SUBDATATYPE', 'URL', 'PROPERTY_KEY_DATATYPE', 'String', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, FILTER_BY_LIST_NAME, FILTER_BY_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (702, 'FD', 'PROPERTY_KEY_SUBDATATYPE', 'JDBCURL', 'PROPERTY_KEY_DATATYPE', 'String', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, FILTER_BY_LIST_NAME, FILTER_BY_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (703, 'FD', 'PROPERTY_KEY_SUBDATATYPE', 'DIRECTORY', 'PROPERTY_KEY_DATATYPE', 'String', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Notification events
--INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
--VALUES (801, 'NOTIFICATION_EVENT', 'INITIATED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (802, 'NOTIFICATION_EVENT', 'PENDING_APPROVAL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (803, 'NOTIFICATION_EVENT', 'SCHEDULED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (804, 'NOTIFICATION_EVENT', 'REJECTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (805, 'NOTIFICATION_EVENT', 'READY', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (806, 'NOTIFICATION_EVENT', 'COMPLETED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (807, 'NOTIFICATION_EVENT', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);

--INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
--VALUES (801, 'NOTIFICATION_EVENT', 'INITIATED', 'Request Creation', 'Request has been created', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (802, 'NOTIFICATION_EVENT', 'PENDING_APPROVAL', 'Request Approval Pending', 'Request is pending approval', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (803, 'NOTIFICATION_EVENT', 'SCHEDULED', 'Request Scheduled', 'Request is pending schedule', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (804, 'NOTIFICATION_EVENT', 'REJECTED', 'Request Approval Rejected', 'Request approval is rejected', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (805, 'NOTIFICATION_EVENT', 'READY', 'Request Deploying', 'Request is deploying', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (806, 'NOTIFICATION_EVENT', 'COMPLETED', 'Request Completed', 'Request is completed', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (807, 'NOTIFICATION_EVENT', 'FAILED', 'Request Failed', 'Request is failed', sysdate, 'anonymous', sysdate,'anonymous', 1);

--INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
--VALUES (801, 'FD', 'NOTIFICATION_EVENT', 'INITIATED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (802, 'FD', 'NOTIFICATION_EVENT', 'PENDING_APPROVAL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (803, 'FD', 'NOTIFICATION_EVENT', 'SCHEDULED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (804, 'FD', 'NOTIFICATION_EVENT', 'REJECTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (805, 'FD', 'NOTIFICATION_EVENT', 'READY', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (806, 'FD', 'NOTIFICATION_EVENT', 'COMPLETED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (807, 'FD', 'NOTIFICATION_EVENT', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Notification types
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (901, 'NOTIFICATION_TYPE', 'EMAIL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (902, 'NOTIFICATION_TYPE', 'USER', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (903, 'NOTIFICATION_TYPE', 'GROUP', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (901, 'NOTIFICATION_TYPE', 'EMAIL', 'EMAIL', 'EMAIL', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (902, 'NOTIFICATION_TYPE', 'USER', 'USER', 'USER', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (903, 'NOTIFICATION_TYPE', 'GROUP', 'GROUP', 'GROUP', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (901, 'FD', 'NOTIFICATION_TYPE', 'EMAIL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (902, 'FD', 'NOTIFICATION_TYPE', 'USER', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (903, 'FD', 'NOTIFICATION_TYPE', 'GROUP', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- REQUEST_STATUS
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1001, 'REQUEST_STATUS', 'INITIATED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1002, 'REQUEST_STATUS', 'PENDING_APPROVAL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1003, 'REQUEST_STATUS', 'SCHEDULED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1004, 'REQUEST_STATUS', 'REJECTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1005, 'REQUEST_STATUS', 'READY', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1006, 'REQUEST_STATUS', 'COMPLETED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1007, 'REQUEST_STATUS', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1008, 'REQUEST_STATUS', 'SUBMITTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1009, 'REQUEST_STATUS', 'ABORTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1001, 'REQUEST_STATUS', 'INITIATED', 'Initiated', 'Initiated', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1002, 'REQUEST_STATUS', 'PENDING_APPROVAL', 'Pending Approval', 'Pending Approval', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1003, 'REQUEST_STATUS', 'SCHEDULED', 'Scheduled', 'Scheduled', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1004, 'REQUEST_STATUS', 'REJECTED', 'Rejected', 'Rejected', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1005, 'REQUEST_STATUS', 'READY', 'Ready', 'Ready', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1006, 'REQUEST_STATUS', 'COMPLETED', 'Completed', 'Completed', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1007, 'REQUEST_STATUS', 'FAILED', 'Failed', 'Failed', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1008, 'REQUEST_STATUS', 'SUBMITTED', 'Submitted', 'Submitted', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1009, 'REQUEST_STATUS', 'ABORTED', 'Aborted', 'Aborted', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1001, 'FD', 'REQUEST_STATUS', 'INITIATED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1002, 'FD', 'REQUEST_STATUS', 'PENDING_APPROVAL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1003, 'FD', 'REQUEST_STATUS', 'SCHEDULED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1004, 'FD', 'REQUEST_STATUS', 'REJECTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1005, 'FD', 'REQUEST_STATUS', 'READY', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1006, 'FD', 'REQUEST_STATUS', 'COMPLETED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1007, 'FD', 'REQUEST_STATUS', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1008, 'FD', 'REQUEST_STATUS', 'SUBMITTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1009, 'FD', 'REQUEST_STATUS', 'ABORTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Task Status (used for both Approval Tasks and Scheduled Tasks)
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1101, 'TASK_STATUS', 'PENDING', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1102, 'TASK_STATUS', 'APPROVED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1103, 'TASK_STATUS', 'REJECTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1104, 'TASK_STATUS', 'VOIDED', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1101, 'TASK_STATUS', 'PENDING', 'Pending', 'Pending', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1102, 'TASK_STATUS', 'APPROVED', 'Approved', 'Approved', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1103, 'TASK_STATUS', 'REJECTED', 'Rejected', 'Rejected', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1104, 'TASK_STATUS', 'VOIDED', 'Voided', 'Voided', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1101, 'FD', 'TASK_STATUS', 'PENDING', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1102, 'FD', 'TASK_STATUS', 'APPROVED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1103, 'FD', 'TASK_STATUS', 'REJECTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1104, 'FD', 'TASK_STATUS', 'VOIDED', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- SCM Type
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1201, 'SCM_TYPE', 'NONE', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1202, 'SCM_TYPE', 'SVN', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1203, 'SCM_TYPE', 'GIT', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1204, 'SCM_TYPE', 'CVS', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1205, 'SCM_TYPE', 'TFVC', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1201, 'SCM_TYPE', 'NONE', 'None', 'None', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1202, 'SCM_TYPE', 'SVN', 'Subversion', 'Subversion', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1203, 'SCM_TYPE', 'GIT', 'Git', 'Git', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1204, 'SCM_TYPE', 'CVS', 'CVS', 'CVS', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1205, 'SCM_TYPE', 'TFVC', 'TFVC', 'TFVC', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1201, 'FD', 'SCM_TYPE', 'NONE', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1202, 'FD', 'SCM_TYPE', 'SVN', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1203, 'FD', 'SCM_TYPE', 'GIT', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1204, 'FD', 'SCM_TYPE', 'CVS', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1205, 'FD', 'SCM_TYPE', 'TFVC', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Project Trigger Type 
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1301, 'TRIGGER_TYPE', 'POLL_SCM', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1302, 'TRIGGER_TYPE', 'MANUAL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1303, 'TRIGGER_TYPE', 'SCHEDULE', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1304, 'TRIGGER_TYPE', 'POST_BUILD', sysdate, 'anonymous', sysdate, 'anonymous', 1);


INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1301, 'TRIGGER_TYPE', 'POLL_SCM', 'Poll SCM', 'Poll SCM', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1302, 'TRIGGER_TYPE', 'MANUAL', 'Manual', 'Manual (UI/API)', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1303, 'TRIGGER_TYPE', 'SCHEDULE', 'Schedule', 'Schedule (UI/API)', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1304, 'TRIGGER_TYPE', 'POST_BUILD', 'Post Build', 'Post Build (UI/API)', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1301, 'FD', 'TRIGGER_TYPE', 'POLL_SCM', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1302, 'FD', 'TRIGGER_TYPE', 'MANUAL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1303, 'FD', 'TRIGGER_TYPE', 'SCHEDULE', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1304, 'FD', 'TRIGGER_TYPE', 'POST_BUILD', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- OS Type
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1401, 'OS_TYPE', 'WINDOWS', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1402, 'OS_TYPE', 'UNIX', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1401, 'OS_TYPE', 'WINDOWS', 'Windows', 'Windows', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1402, 'OS_TYPE', 'UNIX', 'Unix', 'Unix', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1401, 'FD', 'OS_TYPE', 'WINDOWS', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1402, 'FD', 'OS_TYPE', 'UNIX', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Endpoint Connection Type
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1501, 'CONNECTION_TYPE', 'SSH', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1502, 'CONNECTION_TYPE', 'LOCALHOST', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1501, 'CONNECTION_TYPE', 'SSH', 'SSH', 'SSH', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1502, 'CONNECTION_TYPE', 'LOCALHOST', 'localhost', 'localhost', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1501, 'FD', 'CONNECTION_TYPE', 'SSH', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1502, 'FD', 'CONNECTION_TYPE', 'LOCALHOST', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Default types
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1601, 'FD_DEFAULTS_SCRIPT_TYPE', 'EndPointDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1602, 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectSVNSetupDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1603, 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1604, 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectGITSetupDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1605, 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectTFVCSetupDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1606, 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectCVSSetupDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1601, 'FD_DEFAULTS_SCRIPT_TYPE', 'EndPointDefaults', 'EndPointDefaults', 'Endpoint Defaults', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1602, 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectSVNSetupDefaults', 'ProjectSVNSetupDefaults', 'Project SVN Setup Defaults', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1603, 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectDefaults', 'ProjectDefaults', 'Project Defaults', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1604, 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectGITSetupDefaults', 'ProjectGITSetupDefaults', 'Project GIT Setup Defaults', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1605, 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectTFVCSetupDefaults', 'ProjectTFVCSetupDefaults', 'Project TFVC Setup Defaults', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1606, 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectCVSSetupDefaults', 'ProjectCVSSetupDefaults', 'Project CVS Setup Defaults', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1601, 'FD', 'FD_DEFAULTS_SCRIPT_TYPE', 'EndPointDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1602, 'FD', 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectSVNSetupDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1603, 'FD', 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1604, 'FD', 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectGITSetupDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1605, 'FD', 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectTFVCSetupDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1606, 'FD', 'FD_DEFAULTS_SCRIPT_TYPE', 'ProjectCVSSetupDefaults', sysdate, 'anonymous', sysdate, 'anonymous', 1);


-- Instance Sub Group Type (keep it separate to support different value in case of project scm type and instance scm type)
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1702, 'INSTANCE_SUB_GROUP_TYPE', 'SVN', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1703, 'INSTANCE_SUB_GROUP_TYPE', 'GIT', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1704, 'INSTANCE_SUB_GROUP_TYPE', 'CVS', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1705, 'INSTANCE_SUB_GROUP_TYPE', 'TFVC', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1702, 'INSTANCE_SUB_GROUP_TYPE', 'SVN', 'Subversion', 'Subversion', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1703, 'INSTANCE_SUB_GROUP_TYPE', 'GIT', 'Git', 'Git', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1704, 'INSTANCE_SUB_GROUP_TYPE', 'CVS', 'CVS', 'CVS', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1705, 'INSTANCE_SUB_GROUP_TYPE', 'TFVC', 'TFVC', 'TFVC', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1702, 'FD', 'INSTANCE_SUB_GROUP_TYPE', 'SVN', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1703, 'FD', 'INSTANCE_SUB_GROUP_TYPE', 'GIT', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1704, 'FD', 'INSTANCE_SUB_GROUP_TYPE', 'CVS', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1705, 'FD', 'INSTANCE_SUB_GROUP_TYPE', 'TFVC', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Flex field object types
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1801, 'FD_FLEX_FIELD_OBJECT_TYPE', 'DeployRequest', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1801, 'FD_FLEX_FIELD_OBJECT_TYPE', 'DeployRequest', 'DeployRequest', 'Deploy Request', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1801, 'FD', 'FD_FLEX_FIELD_OBJECT_TYPE', 'DeployRequest', sysdate, 'anonymous', sysdate, 'anonymous', 1);


--Test runs
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1901, 'TEST_RUN_STATUS', 'RUNNING', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1902, 'TEST_RUN_STATUS', 'PASSED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (1903, 'TEST_RUN_STATUS', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);


INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1901, 'TEST_RUN_STATUS', 'RUNNING', 'Running', 'Running', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1902, 'TEST_RUN_STATUS', 'PASSED', 'Passed', 'Passed', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1903, 'TEST_RUN_STATUS', 'FAILED', 'Failed', 'Failed', sysdate, 'anonymous', sysdate,'anonymous', 1);


INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1901, 'FD', 'TEST_RUN_STATUS', 'RUNNING', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1902, 'FD', 'TEST_RUN_STATUS', 'PASSED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (1903, 'FD', 'TEST_RUN_STATUS', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);


--Test Results
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2001, 'TEST_RESULT_STATUS', 'SKIPPED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2002, 'TEST_RESULT_STATUS', 'PASSED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2003, 'TEST_RESULT_STATUS', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2004, 'TEST_RESULT_STATUS', 'ERROR', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2001, 'TEST_RESULT_STATUS', 'SKIPPED', 'Skipped', 'Skipped', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2002, 'TEST_RESULT_STATUS', 'PASSED', 'Passed', 'Passed', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2003, 'TEST_RESULT_STATUS', 'FAILED', 'Failed', 'Failed', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2004, 'TEST_RESULT_STATUS', 'ERROR', 'Error', 'Error', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2001, 'FD', 'TEST_RESULT_STATUS', 'SKIPPED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2002, 'FD', 'TEST_RESULT_STATUS', 'PASSED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2003, 'FD', 'TEST_RESULT_STATUS', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2004, 'FD', 'TEST_RESULT_STATUS', 'ERROR', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Template Input Data Type
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2101, 'TEMPLATE_INPUT_DATATYPE', 'String', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2102, 'TEMPLATE_INPUT_DATATYPE', 'Integer', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2103, 'TEMPLATE_INPUT_DATATYPE', 'Boolean', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2104, 'TEMPLATE_INPUT_DATATYPE', 'Long', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2105, 'TEMPLATE_INPUT_DATATYPE', 'Double', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2106, 'TEMPLATE_INPUT_DATATYPE', 'Float', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2101, 'TEMPLATE_INPUT_DATATYPE', 'String', 'String', 'String', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2102, 'TEMPLATE_INPUT_DATATYPE', 'Integer', 'Integer', 'Integer', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2103, 'TEMPLATE_INPUT_DATATYPE', 'Boolean', 'Boolean', 'Boolean', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2104, 'TEMPLATE_INPUT_DATATYPE', 'Long', 'Long', 'Long', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2105, 'TEMPLATE_INPUT_DATATYPE', 'Double', 'Double', 'Double', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2106, 'TEMPLATE_INPUT_DATATYPE', 'Float', 'Float', 'Float', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2101, 'FD', 'TEMPLATE_INPUT_DATATYPE', 'String', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2102, 'FD', 'TEMPLATE_INPUT_DATATYPE', 'Integer', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2103, 'FD', 'TEMPLATE_INPUT_DATATYPE', 'Boolean', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2104, 'FD', 'TEMPLATE_INPUT_DATATYPE', 'Long', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2105, 'FD', 'TEMPLATE_INPUT_DATATYPE', 'Double', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2106, 'FD', 'TEMPLATE_INPUT_DATATYPE', 'Float', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Deploy Priority Scope
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2201, 'FD_DEPLOY_PRIORITY_SCOPE', 'Application', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2202, 'FD_DEPLOY_PRIORITY_SCOPE', 'Folder', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2203, 'FD_DEPLOY_PRIORITY_SCOPE', 'Global', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2201, 'FD_DEPLOY_PRIORITY_SCOPE', 'Application', 'Application', 'Application', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2202, 'FD_DEPLOY_PRIORITY_SCOPE', 'Folder', 'Folder', 'Folder', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2203, 'FD_DEPLOY_PRIORITY_SCOPE', 'Global', 'Global', 'Global', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2201, 'FD', 'FD_DEPLOY_PRIORITY_SCOPE', 'Application', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2202, 'FD', 'FD_DEPLOY_PRIORITY_SCOPE', 'Folder', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2203, 'FD', 'FD_DEPLOY_PRIORITY_SCOPE', 'Global', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Project Type list data
--INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE , CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
--VALUES (2301, 'FD_PROJECT_TYPE', 'GENERAL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2302, 'FD_PROJECT_TYPE', 'EBS', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2303, 'FD_PROJECT_TYPE', 'OracleForms', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (2304, 'FD_PROJECT_TYPE', 'ORACLE_DB', sysdate, 'anonymous', sysdate, 'anonymous', 1);

--INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
--VALUES (2301, 'FD_PROJECT_TYPE', 'GENERAL', 'General', 'General', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2302, 'FD_PROJECT_TYPE', 'EBS', 'EBS', 'EBS', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2303, 'FD_PROJECT_TYPE', 'OracleForms', 'Oracle Forms', 'Oracle Forms', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2304, 'FD_PROJECT_TYPE', 'ORACLE_DB', 'ORACLE_DB', 'Oracle Database', sysdate, 'anonymous', sysdate,'anonymous', 1);

--INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
--VALUES (2301, 'FD', 'FD_PROJECT_TYPE', 'GENERAL', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2302, 'FD', 'FD_PROJECT_TYPE', 'EBS', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2303, 'FD', 'FD_PROJECT_TYPE', 'OracleForms', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (2304, 'FD', 'FD_PROJECT_TYPE', 'ORACLE_DB', sysdate, 'anonymous', sysdate, 'anonymous', 1);


-- Issue tracking related list data
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (3001, 'ITS', '1', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (3001, 'FD', 'ITS', '1', sysdate, 'anonymous', sysdate, 'anonymous', 1);


INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (4001, 'ITS_TICKET_STATUS', '11', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (4002, 'ITS_TICKET_STATUS', '21', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (4003, 'ITS_TICKET_STATUS', '31', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (4004, 'ITS_TICKET_STATUS', '41', sysdate, 'anonymous', sysdate, 'anonymous', 1);


INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (4001, 'ITS_TICKET_STATUS', '11', 'To Do', 'To Do', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (4002, 'ITS_TICKET_STATUS', '21', 'In Progress', 'In Progress', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (4003, 'ITS_TICKET_STATUS', '31', 'In Review', 'In Review', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (4004, 'ITS_TICKET_STATUS', '41', 'Done', 'Done', sysdate, 'anonymous', sysdate,'anonymous', 1);


INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, FILTER_BY_LIST_NAME, FILTER_BY_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (4001, 'FD', 'ITS_TICKET_STATUS', '11', 'ITS', '1', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, FILTER_BY_LIST_NAME, FILTER_BY_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (4002, 'FD', 'ITS_TICKET_STATUS', '21', 'ITS', '1', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, FILTER_BY_LIST_NAME, FILTER_BY_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (4003, 'FD', 'ITS_TICKET_STATUS', '31', 'ITS', '1', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, FILTER_BY_LIST_NAME, FILTER_BY_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (4004, 'FD', 'ITS_TICKET_STATUS', '41', 'ITS', '1', sysdate, 'anonymous', sysdate, 'anonymous', 1);

-- Package Object Execution Status list data
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (5001, 'PACKAGE_OBJECT_EXECUTION_STATUS', 'SUCCESS', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (5002, 'PACKAGE_OBJECT_EXECUTION_STATUS', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (5003, 'PACKAGE_OBJECT_EXECUTION_STATUS', 'SKIPPED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST (LIST_CODE_ID,  LIST_NAME ,  LIST_CODE ,  CREATED_ON ,  CREATED_BY ,  UPDATED_ON ,  UPDATED_BY ,  VERSION_NUMBER ) 
VALUES (5004, 'PACKAGE_OBJECT_EXECUTION_STATUS', 'NOT_ATTEMPTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);

INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (5001, 'PACKAGE_OBJECT_EXECUTION_STATUS', 'SUCCESS', 'Success', 'Success', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (5002, 'PACKAGE_OBJECT_EXECUTION_STATUS', 'FAILED', 'Failed', 'Failed', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (5003, 'PACKAGE_OBJECT_EXECUTION_STATUS', 'SKIPPED', 'Skipped', 'Skipped', sysdate, 'anonymous', sysdate,'anonymous', 1);
INSERT INTO FF.LIST_DISPLAY_DATA (LIST_DISPLAY_DATA_ID, LIST_NAME, LIST_CODE, SHORT_DISPLAY_TEXT, LONG_DISPLAY_TEXT,CREATED_ON , CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (5004, 'PACKAGE_OBJECT_EXECUTION_STATUS', 'NOT_ATTEMPTED', 'Not Attempted', 'Not Attempted', sysdate, 'anonymous', sysdate,'anonymous', 1);

INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (5001, 'FD', 'PACKAGE_OBJECT_EXECUTION_STATUS', 'SUCCESS', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (5002, 'FD', 'PACKAGE_OBJECT_EXECUTION_STATUS', 'FAILED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (5003, 'FD', 'PACKAGE_OBJECT_EXECUTION_STATUS', 'SKIPPED', sysdate, 'anonymous', sysdate, 'anonymous', 1);
INSERT INTO FF.LIST_FILTER_DATA (LIST_FILTER_DATA_ID, FILTER_NAME, FILTERED_LIST_NAME, FILTERED_LIST_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, VERSION_NUMBER) 
VALUES (5004, 'FD', 'PACKAGE_OBJECT_EXECUTION_STATUS', 'NOT_ATTEMPTED', sysdate, 'anonymous', sysdate, 'anonymous', 1);

