package flexagon.fusion.hrdemo.model.appmodules.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 09 09:53:25 CDT 2015
// ---------------------------------------------------------------------
public interface HRUIAM
  extends ApplicationModule
{

}

