prompt --install
@application/set_environment.sql
@application/delete_application.sql
@application/create_application.sql
@application/shared_components/navigation/lists/navigation_tabs.sql
@application/shared_components/navigation/lists/administration.sql
@application/shared_components/navigation/lists/admin_reports.sql
@application/shared_components/navigation/lists/task_actions.sql
@application/shared_components/navigation/lists/project_actions.sql
@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@application/plugin_settings.sql
@application/shared_components/security/authorizations/team_members.sql
@application/shared_components/navigation/navigation_bar.sql
@application/shared_components/logic/application_items.sql
@application/shared_components/logic/application_computations.sql
@application/shared_components/logic/application_settings.sql
@application/shared_components/navigation/tabs/standard.sql
@application/shared_components/navigation/tabs/parent.sql
@application/shared_components/user_interface/lovs/link_types.sql
@application/shared_components/user_interface/lovs/milestones.sql
@application/shared_components/user_interface/lovs/projects.sql
@application/shared_components/user_interface/lovs/status.sql
@application/shared_components/user_interface/lovs/tasks.sql
@application/shared_components/user_interface/lovs/tasks_with_dates.sql
@application/shared_components/user_interface/lovs/team_members.sql
@application/shared_components/user_interface/lovs/timeframe.sql
@application/shared_components/user_interface/lovs/username.sql
@application/pages/page_groups.sql
@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@application/shared_components/user_interface/templates/page/left_side_column.sql
@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@application/shared_components/user_interface/templates/page/login.sql
@application/shared_components/user_interface/templates/page/master_detail.sql
@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@application/shared_components/user_interface/templates/page/modal_dialog.sql
@application/shared_components/user_interface/templates/page/right_side_column.sql
@application/shared_components/user_interface/templates/page/standard.sql
@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@application/shared_components/user_interface/templates/button/icon.sql
@application/shared_components/user_interface/templates/button/text.sql
@application/shared_components/user_interface/templates/button/text_with_icon.sql
@application/shared_components/user_interface/templates/region/inline_popup.sql
@application/shared_components/user_interface/templates/region/content_block.sql
@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@application/shared_components/user_interface/templates/region/alert.sql
@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@application/shared_components/user_interface/templates/region/buttons_container.sql
@application/shared_components/user_interface/templates/region/carousel_container.sql
@application/shared_components/user_interface/templates/region/collapsible.sql
@application/shared_components/user_interface/templates/region/hero.sql
@application/shared_components/user_interface/templates/region/inline_dialog.sql
@application/shared_components/user_interface/templates/region/interactive_report.sql
@application/shared_components/user_interface/templates/region/login.sql
@application/shared_components/user_interface/templates/region/standard.sql
@application/shared_components/user_interface/templates/region/tabs_container.sql
@application/shared_components/user_interface/templates/region/title_bar.sql
@application/shared_components/user_interface/templates/region/wizard_container.sql
@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@application/shared_components/user_interface/templates/list/badge_list.sql
@application/shared_components/user_interface/templates/list/cards.sql
@application/shared_components/user_interface/templates/list/links_list.sql
@application/shared_components/user_interface/templates/list/media_list.sql
@application/shared_components/user_interface/templates/list/menu_bar.sql
@application/shared_components/user_interface/templates/list/menu_popup.sql
@application/shared_components/user_interface/templates/list/navigation_bar.sql
@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@application/shared_components/user_interface/templates/list/tabs.sql
@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@application/shared_components/user_interface/templates/list/wizard_progress.sql
@application/shared_components/user_interface/templates/report/media_list.sql
@application/shared_components/user_interface/templates/report/alerts.sql
@application/shared_components/user_interface/templates/report/badge_list.sql
@application/shared_components/user_interface/templates/report/cards.sql
@application/shared_components/user_interface/templates/report/comments.sql
@application/shared_components/user_interface/templates/report/search_results.sql
@application/shared_components/user_interface/templates/report/standard.sql
@application/shared_components/user_interface/templates/report/timeline.sql
@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@application/shared_components/user_interface/templates/label/required_floating.sql
@application/shared_components/user_interface/templates/label/optional_floating.sql
@application/shared_components/user_interface/templates/label/hidden.sql
@application/shared_components/user_interface/templates/label/optional.sql
@application/shared_components/user_interface/templates/label/optional_above.sql
@application/shared_components/user_interface/templates/label/required.sql
@application/shared_components/user_interface/templates/label/required_above.sql
@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@application/shared_components/user_interface/templates/popuplov.sql
@application/shared_components/user_interface/templates/calendar/calendar.sql
@application/shared_components/user_interface/themes.sql
@application/shared_components/user_interface/theme_style.sql
@application/shared_components/user_interface/theme_files.sql
@application/shared_components/user_interface/theme_display_points.sql
@application/shared_components/user_interface/template_opt_groups.sql
@application/shared_components/user_interface/template_options.sql
@application/shared_components/logic/build_options.sql
@application/shared_components/globalization/language.sql
@application/shared_components/globalization/messages.sql
@application/shared_components/globalization/dyntranslations.sql
@application/shared_components/user_interface/shortcuts/ok_to_get_next_prev_pk_value.sql
@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@application/shared_components/security/authentications/application_express_accounts.sql
@application/shared_components/plugins/region_type/com_oracle_apex_sampleappfooter.sql
@application/shared_components/plugins/region_type/com_oracle_apex_badge_list.sql
@application/user_interfaces.sql
@application/user_interfaces/combined_files.sql
@application/pages/page_00001.sql
@application/pages/page_00002.sql
@application/pages/page_00003.sql
@application/pages/page_00004.sql
@application/pages/page_00005.sql
@application/pages/page_00006.sql
@application/pages/page_00007.sql
@application/pages/page_00008.sql
@application/pages/page_00009.sql
@application/pages/page_00010.sql
@application/pages/page_00011.sql
@application/pages/page_00012.sql
@application/pages/page_00013.sql
@application/pages/page_00014.sql
@application/pages/page_00015.sql
@application/pages/page_00016.sql
@application/pages/page_00017.sql
@application/pages/page_00018.sql
@application/pages/page_00019.sql
@application/pages/page_00020.sql
@application/pages/page_00021.sql
@application/pages/page_00022.sql
@application/pages/page_00023.sql
@application/pages/page_00024.sql
@application/pages/page_00025.sql
@application/pages/page_00026.sql
@application/pages/page_00027.sql
@application/pages/page_00028.sql
@application/pages/page_00029.sql
@application/pages/page_00030.sql
@application/pages/page_00031.sql
@application/pages/page_00101.sql
@application/pages/page_00102.sql
@application/pages/page_00200.sql
@application/pages/page_00210.sql
@application/pages/page_00220.sql
@application/pages/page_00221.sql
@application/pages/page_00222.sql
@application/pages/page_00230.sql
@application/pages/page_00231.sql
@application/pages/page_00240.sql
@application/pages/page_00241.sql
@application/end_environment.sql
