package flexagon.fusion.hrdemo.model.entities;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 20 17:26:01 CDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobHistoryEODefImpl
  extends EntityDefImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public JobHistoryEODefImpl()
  {
  }
}

